from common import add,passages
TIPS={'main_idea':'Choose the statement that covers the whole passage, not just one detail.','detail':'Return to the named paragraph and match the exact detail.','inference':'Choose what the evidence supports without adding an unstated assumption.','vocabulary_context':'Substitute each meaning into the original sentence.','structure':'Ask what the paragraph or example contributes to the passage.','literary':'Connect the literary device or character judgment to specific words and actions.'}
def passage(title,genre,paragraphs,data):
 pid=f'passage-a1-{len(passages)+1:02}'
 passages.append(dict(id=pid,revision=1,title=title,genre=genre,paragraphs=paragraphs,provenance={'origin':'original_agent_authored','date':'2026-09-27'},reviewStatus='pending_human_review'))
 for line in data.strip().splitlines():
  skill,stem,key,a,b,c,why,ev,diff=line.split('|')
  add('reading',skill,stem,key,[a,b,c],why,TIPS[skill],int(diff),f'{genre}-{skill}',passageId=pid,passageRevision=1,evidenceParagraphs=[int(i) for i in ev.split(',')])
passage('The Unlabeled Drawer','fiction',[
'On her first afternoon helping at the repair cafe, Mara arranged the screwdrivers by size and wiped every table twice. Across the room, Mr. Imani opened an old radio. Mara hoped he would ask her to repair something important. Instead, he handed her a drawer full of mixed screws and asked her to sort them. She worked quickly, making neat piles according to color.',
'When Mr. Imani returned, he picked two silver screws from different piles. One was long and thin; the other was short and wide. "Would these do the same job?" he asked. Mara shook her head. He set a ruler beside the drawer and went back to the radio without moving her piles.',
'Mara began again, this time comparing length, width, and the shape of each head. Later, Mr. Imani asked for a short screw with a flat head. She found it immediately. As he secured the radio cover, Mara pulled another unsorted drawer toward her. This time she left the polishing cloth on the table.'
],'''
main_idea|Which statement best expresses the story's central idea?|Careful observation can make an ordinary task meaningful.|Fast work is always more useful than careful work.|Repairing radios requires expensive tools.|An organized room needs no further work.|Mara moves from seeking impressive work to recognizing the value of sorting by useful features.|1,2,3|2
detail|How does Mara first sort the screws?|By color|By length|By width|By head shape|Paragraph 1 explicitly describes piles according to color.|1|1
inference|Why does Mr. Imani leave the ruler rather than sort the screws himself?|He wants Mara to work out a better system.|He has decided the drawer cannot be organized.|He needs Mara to polish the ruler.|He wants all silver screws discarded.|His comparison question and the ruler guide Mara without doing the task for her.|2,3|2
vocabulary_context|In paragraph 3, secured most nearly means what?|fastened|hid|borrowed|examined|Mr. Imani uses a screw to fasten the radio cover.|3|1
literary|What does Mara's decision to pull over another drawer suggest?|Her interest in the work has grown.|She still thinks polishing is the only useful job.|She intends to undo the completed sorting.|She wants to hide her earlier mistake.|She voluntarily continues the task after seeing its practical value.|3|2
structure|What is the main purpose of the two different silver screws in paragraph 2?|They reveal a weakness in Mara's first sorting method.|They show that all silver screws are interchangeable.|They explain why the radio cannot be fixed.|They establish that color is the best way to sort.|Their shared color but different dimensions exposes the limitation of grouping by color.|2|2
''')
passage('A Roof That Holds Rain','expository',[
'When rain strikes an ordinary roof, much of the water quickly travels through gutters and into drains. On a planted roof, a layer of growing material absorbs some of that water. Plants use part of the stored moisture, and some returns to the air through evaporation. The water that does reach the drain may arrive more slowly.',
'A planted roof is not simply a garden placed on top of a building. Designers must account for the weight of wet growing material. They also include layers that protect the roof from roots and keep water from entering the rooms below. Plants are selected for the roof\'s light, wind, and water conditions.',
'These roofs can help manage runoff, but their performance varies. A roof that is already soaked cannot store as much of the next storm as a dry one. Measuring only one gentle shower would therefore give an incomplete picture. Several storms, with different conditions, provide a better test.'
],'''
main_idea|What is the passage mainly explaining?|How planted roofs manage rain and what limits their performance|Why all buildings should have the same roof design|How gutters can replace every drainage system|Why rooftop plants need no maintenance|All three paragraphs address water handling, design requirements and variable performance.|1,2,3|2
detail|Why must designers consider wet growing material?|It adds weight that the building must support.|It prevents all evaporation.|It removes the need for protective layers.|It guarantees that roots cannot spread.|Paragraph 2 specifically identifies the weight of wet growing material as a design concern.|2|1
inference|Which condition would probably reduce a planted roof's ability to store a new shower?|The growing material is already saturated.|The previous week was dry.|The roof has a protective root barrier.|The plants were chosen for local wind conditions.|Paragraph 3 says a soaked roof has less available storage for another storm.|3|2
vocabulary_context|In paragraph 3, runoff refers to what?|Water flowing away from a surface|Material carried onto a roof for planting|Moisture taken up only by plant roots|Air moving across the roof|The passage contrasts water stored on the roof with water leaving through drains.|1,3|2
structure|Why does the author mention a single gentle shower?|To illustrate a test that would be too limited|To identify the only storm worth measuring|To prove every planted roof performs identically|To show that measurements are unnecessary|The example supports the need to measure several storms under different conditions.|3|2
inference|Which statement would the author most likely support?|A roof's benefits should be evaluated under varied conditions.|One successful storm test establishes performance in all weather.|Protective layers matter only on unplanted roofs.|Planted roofs can store an unlimited amount of water.|The author repeatedly qualifies performance and calls for varied testing.|2,3|3
''')
passage('The Map with Two Routes','fiction',[
'Jun unfolded the map his grandfather had drawn for their walk to the old lookout. A red line climbed directly up the hill; a blue line wandered around its base before rising through the trees. Jun tapped the red line. "That one is shorter." His grandfather handed him the map. "Then you can lead."',
'For the first ten minutes, Jun felt pleased with his choice. Then the path grew steep and loose stones shifted under his shoes. At a bend, he stopped to catch his breath. Through the trees he could see the blue route, where two walkers were moving steadily along a gentler slope. He studied the map again, noticing the closely spaced elevation lines around the red path.',
'At the lookout, his grandfather asked which way they should return. Jun traced the blue line with one finger. "It is longer on paper," he said, "but paper does not get tired." His grandfather smiled and let Jun fold the map.'
],'''
main_idea|What does Jun learn during the walk?|The shortest route is not always the easiest.|Maps cannot provide useful information.|The older person should always choose the route.|Long paths always take less time.|Jun's experience makes him consider steepness as well as distance.|1,2,3|2
detail|Which feature does Jun notice only after the climb becomes difficult?|Closely spaced elevation lines|A missing bridge|The lookout's opening hours|A third route in green|Paragraph 2 names the elevation lines he studies after stopping.|2|1
inference|Why does the grandfather let Jun lead?|He allows Jun to learn from making a choice.|He has never seen the map before.|He refuses to walk the blue route.|He cannot read any maps.|He offers the choice and later asks Jun to choose again, supporting learning through experience.|1,3|2
vocabulary_context|In paragraph 2, steadily most nearly means what?|At a consistent pace|Without any direction|With frequent sudden stops|As quickly as possible|The walkers continue along the gentler slope without Jun's described struggle.|2|1
literary|What does Jun mean by saying that paper does not get tired?|A drawn distance does not show the effort he experienced.|The map has become too old to use.|The blue route is absent from the map.|He wishes the map were made of cloth.|His comment contrasts the simple line on paper with physical fatigue.|2,3|3
structure|How does Jun's attention to the map change?|He first considers distance, then also considers terrain.|He first trusts the map, then throws it away.|He first follows blue, then changes to red.|He first reads elevation, then ignores it.|The opening focuses on the shorter line; paragraph 2 adds elevation as a factor.|1,2|2
''')
passage('Counting the Quiet Visitors','expository',[
'A school nature club wanted to learn which flowers attracted visiting insects. Students first planned to count visitors whenever they had a free moment. Their advisor asked whether a five-minute count on a cold morning could fairly be compared with a twenty-minute count on a warm afternoon. The students revised their plan.',
'They chose equal observation periods and recorded the weather as well as the flower patch. They also agreed on what counted as a visit: an insect had to land on a flower, not merely fly past it. Because they could not reliably identify every species, they used broad categories such as bee, butterfly, and other insect. Uncertain observations were marked rather than guessed.',
'After two weeks, one flower patch had the highest total. The club did not call it the best flower for every garden. That patch also received more afternoon sun. Next month, the students would compare patches with more similar light conditions. Their first study had produced both a result and a better question.'
],'''
main_idea|Which statement best summarizes the passage?|Careful counting requires consistent methods and cautious conclusions.|A large insect count always identifies the best garden flower.|Students should avoid studies with uncertain observations.|Weather matters less than the number of students counting.|The revised procedure and qualified conclusion emphasize reliable methods.|1,2,3|2
detail|What must an insect do to count as a visit?|Land on a flower|Fly above the garden|Appear in a photograph|Remain for twenty minutes|Paragraph 2 supplies this operational definition.|2|1
inference|Why were observation periods made equal?|Different counting durations could distort the comparison.|Every insect visit lasts the same time.|Cold mornings always have more insects.|The students wanted to stop recording weather.|A longer counting period could accumulate more visits even with the same visit rate.|1,2|2
vocabulary_context|In paragraph 1, revised most nearly means what?|changed|abandoned forever|memorized|announced publicly|The students modify the plan in response to the advisor's concern.|1,2|1
structure|What role does the final paragraph play?|It explains a limitation and proposes a follow-up study.|It proves that all earlier observations were false.|It gives instructions for identifying every insect species.|It replaces the study with an unrelated project.|The sunlight difference limits the conclusion and motivates the next comparison.|3|2
inference|Which new comparison would best address the club's remaining question?|Different flower types observed for equal periods in similar sunlight|One patch observed twice as long as all others|Only insects that students can name exactly|A sunny patch in summer and a shaded patch in winter|Similar light and observation periods better isolate the flower-type comparison.|2,3|3
''')
passage('A Seat at the Table','fiction',[
'The robotics group had already chosen a design by the time Esme arrived from orchestra practice. On the board, a wide base supported a tall arm. Esme set down her violin case and asked how the machine would turn in the narrow course. "We can adjust it later," said Cal, reaching for the parts box.',
'Esme almost let the question go. Instead, she put two rulers on the table, the same distance apart as the course walls. Cal placed the base between them. It fit while pointing forward, but one corner struck a ruler as he tried to turn it. For a moment, no one spoke. Then Cal pushed the parts box aside and picked up the eraser.',
'They spent the rest of the meeting drawing a narrower base. At the next meeting, Cal left a blank space on the board under the heading "Questions before building." Esme arrived late again, but this time three teammates turned toward her before opening the parts box.'
],'''
main_idea|What is the central idea of this story?|Testing an overlooked concern can improve a group's work.|A group should finish building before asking questions.|Late arrivals should make every design decision.|Music practice prevents successful teamwork.|Esme's concern and demonstration lead to a better design and process.|1,2,3|2
detail|Why does the base fail Esme's test?|A corner hits a ruler while turning.|The arm is too short to reach the table.|The base cannot move forward at all.|A motor stops working.|Paragraph 2 describes the corner striking a ruler during the turn.|2|1
inference|What does Cal's use of the eraser show?|He is willing to revise the design.|He wants to erase Esme's name.|He has decided to cancel robotics.|He believes the test proved nothing.|He changes from reaching for parts to revising the drawing after the failed test.|2,3|2
vocabulary_context|In paragraph 1, adjust most nearly means what?|modify|celebrate|protect|describe|Cal proposes changing the design later.|1|1
literary|Which description best fits Esme?|She is hesitant but willing to support her concern with evidence.|She is eager to embarrass everyone without offering help.|She is uninterested in how the robot works.|She is certain that every other design must fail.|She almost stays silent, then demonstrates a specific problem constructively.|2|2
structure|Why does the author repeat the detail that Esme arrives late?|To highlight the change in how the group responds to her|To show that the meetings never begin on time|To explain why the robot uses rulers|To prove that orchestra and robotics are identical|The same circumstance produces a different response after the group values her questions.|1,3|3
''')
passage('Why Keep the Rough Draft?','argument',[
'A finished essay can make writing look like a straight path from an idea to polished sentences. A folder of drafts tells a different story. An introduction disappears, a weak example gives way to a stronger one, and a conclusion changes the writer\'s understanding of the original question. Keeping these earlier versions can make that work visible.',
'This does not mean saving every accidental keystroke. A useful collection might include the first complete draft, a version after major revision, and the final piece. Beside each, the writer can note one important change and the reason for it. Such notes turn a pile of pages into evidence of decisions.',
'Some students worry that showing early work will expose mistakes. Yet a draft is not a claim of perfection. It gives a teacher a chance to discuss strategies that the final essay alone might conceal. Judged thoughtfully, the collection rewards improvement as well as the final result.'
],'''
main_idea|What does the author recommend?|Saving selected drafts with notes about important revisions|Saving every keystroke without explanation|Grading only the first attempt at an essay|Avoiding revision once an idea is written|The second paragraph gives the specific recommendation supported throughout.|1,2,3|2
detail|Which version does the author explicitly suggest keeping?|A version after major revision|Only a list of spelling errors|Every unfinished sentence|Only a teacher's model essay|Paragraph 2 names a version after major revision among the suggested selections.|2|1
inference|Why would notes make the draft collection more useful?|They explain the thinking behind changes.|They guarantee that no mistakes remain.|They make the final essay unnecessary.|They replace the need to read the drafts.|The notes provide reasons for decisions, making the process interpretable.|2|2
vocabulary_context|In paragraph 3, conceal most nearly means what?|hide|correct|encourage|repeat|The finished essay may hide strategies that earlier versions reveal.|3|1
structure|Why does the author include students' concern about exposing mistakes?|To acknowledge an objection and respond to it|To conclude that drafts should be destroyed|To argue that mistakes matter more than ideas|To introduce an unrelated problem about handwriting|The concern is followed by an explanation of the value of imperfect drafts.|3|2
inference|Which grading practice best matches the author's view?|Considering both the final essay and documented improvement|Ignoring the final essay entirely|Penalizing every crossed-out sentence|Giving the highest grade to the thickest folder|The last sentence explicitly values improvement as well as the final result.|3|2
''')
passage('The Last Light','fiction',[
'Every evening, Arun watched a square of light appear in the workshop across the alley. His neighbor, Mrs. Bell, repaired clocks there. The tiny room held a chorus of ticks, but from Arun\'s window he could hear only the deep chime of the clock nearest the door. One evening the square stayed dark.',
'The next day, a sign appeared: "Moving Saturday." Arun wanted to ask Mrs. Bell where she was going, but each time he approached, she was carrying another box. On Friday he finally knocked. "I will miss the clock," he said. Mrs. Bell looked at the bare wall by the door. "It belongs to the new library now. Perhaps you will hear it there."',
'On Saturday, Arun helped carry the last box to her van. That evening the alley was dark again. The following Monday, he entered the library to return a book. A familiar chime rolled through the reading room. He stood still until the final note faded, then walked toward the desk with the book held a little less tightly.'
],'''
main_idea|Which theme is best supported by the story?|A familiar thing can offer comfort during change.|Every move permanently ends all friendships.|Old clocks are more useful than books.|A neighborhood must remain exactly the same.|The familiar chime comforts Arun after the workshop closes.|1,2,3|2
detail|Where does the clock go?|To the new library|Into Arun's bedroom|To the school office|Into Mrs. Bell's van for sale|Mrs. Bell states that the clock belongs to the new library.|2|1
inference|What does Arun holding the book less tightly suggest?|He feels more at ease.|He has decided not to return the book.|He is angry with the librarian.|He has forgotten Mrs. Bell.|The relaxation follows the reassuring familiar sound.|3|3
vocabulary_context|In paragraph 1, a chorus of ticks suggests what?|Many clock sounds occurring together|A single clock that never works|People singing about clocks|Silence inside the workshop|The workshop contains many clocks, whose ticks are compared to a chorus.|1|2
literary|Why is sound important in the story?|The chime connects Arun's old routine with a new place.|It proves that the alley is always noisy.|It tells the reader exactly how old the clock is.|It prevents Arun from speaking to Mrs. Bell.|The repeated sound provides continuity between the workshop and library.|1,3|2
structure|What contrast organizes the ending?|The dark workshop and the familiar sound in the library|The clock's price and the cost of the book|The van's size and the workshop's height|Friday's weather and Monday's weather|The dark alley marks loss, while the library chime supplies a comforting continuation.|3|2
''')
passage('Reading an Old Photograph','expository',[
'A photograph of a crowded town square seems to offer a direct window into the past. Yet the image does not explain everything it shows. People may have gathered for a market, a parade, or an announcement. Without other evidence, choosing one explanation can turn an observation into a guess.',
'An investigator begins with details that are actually visible: a banner, a shop sign, the position of shadows. Next come questions. Can the shop name be found in a directory? Does a newspaper describe an event with the same banner? The date written on the back of the photograph may help, but it should also be checked; labels can be added much later.',
'Even after research, some uncertainty may remain. A careful caption can distinguish what is known from what is likely. "Crowd in the square, probably during the spring fair" is more informative than an unsupported exact claim. Uncertainty, clearly stated, can make an account more trustworthy rather than less.'
],'''
main_idea|What is the main point of the passage?|Historical photographs should be interpreted with evidence and stated uncertainty.|Photographs never provide useful historical information.|Every handwritten label is accurate.|A detailed caption should avoid mentioning uncertainty.|All paragraphs distinguish visible evidence from unsupported assumptions.|1,2,3|2
detail|Why should a date on the back be checked?|Someone may have added it much later.|Photographs cannot be dated at all.|Shop signs never appear in photographs.|Dates always describe the photographer's birthday.|Paragraph 2 warns that labels can be added later.|2|1
inference|Which observation would most directly help verify a suspected parade?|A newspaper account describing the same visible banner|A guess based only on the size of the crowd|The researcher's preference for parades|A modern picture of a different town|Matching a visible detail to another source offers corroboration.|2|2
vocabulary_context|In paragraph 3, account most nearly means what?|description|bank deposit|calculation|permission|The passage discusses a trustworthy historical description.|3|1
structure|What is the purpose of the sample caption?|To demonstrate how to separate certainty from probability|To prove that every town held a spring fair|To supply the only permitted wording for captions|To show that research is a waste of time|Probably explicitly signals the claim's level of certainty.|3|2
inference|Which statement would the author most likely reject?|A crowded square by itself proves that a parade occurred.|Visible details can guide further questions.|Newspapers may help explain an image.|Some conclusions remain uncertain after research.|Paragraph 1 lists several possible causes for a crowd and warns against guessing.|1|2
''')
passage('The Borrowed Paddle','fiction',[
'Leah was certain she knew how to canoe. She had watched her older cousins cross the lake every summer, their paddles dipping in a clean rhythm. When her uncle offered a short lesson near the shore, she said she would rather go straight to the island. He placed a paddle in her hands and asked her to guide the canoe around a floating marker first.',
'Leah paddled hard on one side. The canoe turned away from the marker. She switched sides and paddled even harder; now it swung the other way. Her uncle did not reach for the paddle. "Try less," he said. She made a smaller stroke and watched what happened. After several slow attempts, the canoe curved around the marker.',
'The island still looked close, but Leah noticed ripples farther out where the wind crossed the open water. She rested the paddle across her knees. "Can we practice coming back to shore?" she asked. Her uncle nodded, and this time she waited for the instructions.'
],'''
main_idea|What does Leah's experience teach her?|Watching a skill is different from learning to perform it.|Strength alone determines canoeing ability.|Lessons are useful only after a long journey.|The lake is too dangerous for any practice.|Her confidence from watching gives way to seeking instruction after trying the skill.|1,2,3|2
detail|What first happens when Leah paddles hard on one side?|The canoe turns away from the marker.|The canoe stops at the island.|The paddle breaks.|The marker sinks.|Paragraph 2 directly describes the canoe's initial turn.|2|1
inference|Why does Leah ask to practice returning to shore?|She recognizes that she needs more control before going farther.|She wants to avoid ever using a canoe again.|She has already reached the island.|She believes smaller strokes cannot help.|Her practice and observation of wind prompt a more cautious goal.|2,3|2
vocabulary_context|In paragraph 1, rhythm most nearly means what?|regular pattern|sudden accident|great distance|loud argument|The cousins' repeated paddle movements form a regular pattern.|1|1
literary|How does Leah change?|She becomes more willing to learn from instruction.|She becomes more certain that lessons are unnecessary.|She loses interest in the lake entirely.|She stops observing the canoe's movement.|Her final waiting for instructions contrasts with her initial wish to skip the lesson.|1,3|2
structure|Why does the author mention ripples farther out?|To show a condition Leah now notices when judging her readiness|To indicate that the island has moved|To explain the color of the canoe|To reveal that the uncle caused all the waves|The wind beyond the sheltered practice area helps explain her revised decision.|3|3
''')
passage('A Fair Test of Packaging','expository',[
'Two student teams designed containers to protect an egg during a short drop. Team A used folded paper supports; Team B used a bed of soft fabric. When Team A\'s egg survived and Team B\'s cracked, several observers declared paper the better material. Their teacher asked them to compare how the trials had been carried out.',
'Team A had dropped its container from a lower shelf. Team B had used a higher one. The containers also differed in size, and only one egg had been tested in each. The result showed what happened in those two trials, but it did not isolate the effect of the cushioning material.',
'For a new test, the teams chose matching containers and the same drop height. They planned several trials with each material and recorded whether each egg cracked. Even this study would answer a limited question: how those particular designs performed under the chosen conditions. It would not identify the best package for every fragile object.'
],'''
main_idea|What is the passage mainly about?|Designing a comparison that supports a limited, fair conclusion|Proving that paper always protects eggs better than fabric|Showing that dropping eggs cannot teach anything|Choosing the cheapest possible container|The passage identifies confounding differences and improves the comparison.|1,2,3|2
detail|Which difference made the original trials hard to compare?|The containers were dropped from different heights.|Both teams used identical containers.|Each team tested many eggs.|Both eggs survived.|Paragraph 2 identifies the lower and higher shelves.|2|1
inference|Why are several trials better than one trial per material?|They reduce reliance on a single result that may not be typical.|They guarantee that no eggs will crack.|They remove the need to use equal heights.|They prove the best material for all objects.|Repeated trials provide more evidence than a single observation, without making universal guarantees.|2,3|3
vocabulary_context|In paragraph 2, isolate most nearly means what?|distinguish separately|hide permanently|make larger|carry outside|The test should separate the material's effect from other differences.|2|2
structure|What does the final sentence do?|It limits the reach of the study's conclusion.|It cancels the plan for the new test.|It explains how to fold the paper supports.|It repeats the original unsupported declaration.|The sentence says the test cannot establish the best package for every object.|3|2
inference|Which claim could the revised study best support?|One tested design protected eggs more often at the chosen height.|Paper is best for every fragile item.|Container size never affects protection.|A single successful drop proves a design cannot fail.|The proposed controls and repeated trials support a comparison within those conditions.|3|3
''')
passage('The Window Box','fiction',[
'Tomas planted seeds in the window box outside his apartment and checked them before school each morning. For a week, the soil looked unchanged. His sister suggested digging up a seed to see what was wrong. Tomas reached for a spoon, then read the packet again. It said seedlings could take ten to fourteen days to appear. He put the spoon away.',
'On the eleventh morning, a pale hook rose through the soil. By evening it had straightened into a tiny stem. Tomas marked its height on a strip of paper taped beside the box. Some days he could see no difference. On those days, he compared the newest mark with the first instead of with yesterday\'s.',
'When his sister returned from a week at camp, she pointed to the leaves stretching over the box. "They grew so fast!" she said. Tomas looked at the small staircase of marks on the paper. He smiled and brought out another packet of seeds.'
],'''
main_idea|Which idea does the story emphasize?|Patient observation can reveal gradual progress.|Seeds should be dug up whenever growth is not visible.|Daily changes are always large and obvious.|Plants grow only while people are away.|Tomas waits and uses marks to recognize growth over time.|1,2,3|2
detail|When does the first visible shoot appear?|On the eleventh morning|On the seventh morning|After Tomas digs up a seed|After his sister plants new seeds|Paragraph 2 explicitly gives the eleventh morning.|2|1
inference|Why does Tomas compare the newest mark with the first?|A longer interval makes small changes easier to notice.|The first mark predicts the plant's final height exactly.|He has lost all the other marks.|He wants to stop observing the plant.|The passage says some daily differences are invisible, while cumulative growth can be seen.|2|2
vocabulary_context|In paragraph 2, pale most nearly means what?|light in color|very loud|fully grown|completely dry|Pale describes the young shoot's color.|2|1
literary|What does the small staircase of marks represent?|The plant's gradual increase in height|A set of steps leading to the apartment|The number of seeds that failed|The days Tomas forgot to water|The marks record successive heights and resemble rising steps.|2,3|2
structure|How does the sister's final comment contrast with Tomas's experience?|She sees a large change at once, while he has watched small changes accumulate.|She has kept a more detailed growth chart.|She knows the seeds never sprouted.|She sees no change, while he sees fully grown trees.|Her absence makes the growth seem fast; he knows the daily progression.|1,2,3|3
''')
passage('Making Room for Silence','argument',[
'A community center plans to turn an unused room into a quiet study space. Some residents would rather use every room for meetings and classes. Those activities matter, but a room without a scheduled speaker or group can serve another need: a place where people can concentrate on their own work.',
'At home, a student may share a table with younger siblings. An adult studying for a certificate may have no separate desk. A quiet room does not have to be elaborate. Good lighting, seats, work surfaces, and clear expectations about noise may be enough. Locating it away from the music room would help.',
'The center should begin with a trial rather than a permanent promise. For six weeks, it could record how often the room is used and invite comments. If few people come, the schedule or setup could change. A quiet room deserves a fair test, not an assumption that an unscheduled space is an unused one.'
],'''
main_idea|What is the author's main claim?|The center should test a quiet study room as a useful service.|All meetings and classes should be canceled.|A study room requires expensive equipment.|Every resident has a suitable workspace at home.|The passage argues for a limited trial of a distinct service.|1,2,3|2
detail|How long is the proposed trial?|Six weeks|Six days|Six months|One school year|Paragraph 3 specifies six weeks.|3|1
inference|Why are both a student and an adult mentioned?|To show that different residents may need quiet workspace.|To suggest adults should exclude students from the room.|To show that only certificate students need desks.|To prove every household has younger siblings.|The two examples illustrate needs across age groups.|2|2
vocabulary_context|In paragraph 2, elaborate most nearly means what?|complicated or richly equipped|silent at all times|open to the public|located upstairs|The following simple requirements contrast with a complicated setup.|2|2
structure|Why does the author propose collecting usage records and comments?|To evaluate and adjust the idea using evidence.|To ensure the room can never change.|To replace every class with a survey.|To identify which residents should be excluded.|The next sentence describes changing the schedule or setup if necessary.|3|2
inference|Which response best reflects the author's position if initial use is low?|Investigate changes to the schedule or setup before judging the idea.|Declare all quiet spaces useless everywhere.|Ignore the records and make no changes.|Turn every meeting room into a study room immediately.|The author explicitly allows adjustment based on the trial.|3|2
''')
# Four seven-question groups complete the 100-item bank.
passage('The Poster That Changed','fiction',[
'Inez spent Saturday painting a poster for the neighborhood cleanup. Large letters announced the date above a bright drawing of the river. She taped it inside the bakery window and stepped back proudly. On Monday, her neighbor Mr. Cho asked what time volunteers should arrive. Inez pointed at the poster, then realized the time was not there.',
'She added the time in a corner. Later, a woman carrying groceries asked where the group would meet. Inez frowned at the crowded poster. She had used nearly all the space for the river. At home, she sketched a new version with three clear lines: when, where, and what to bring. The drawing became smaller.',
'By Friday, the sign-up sheet beside the poster was almost full. Inez still liked her first painting better as a picture. But when a child read the new poster aloud and told his mother exactly where to go, Inez decided to keep the second version in the window.'
],'''
main_idea|What does Inez learn?|A poster's design should serve its purpose.|A picture is always more important than information.|Neighbors never read signs carefully.|Every poster should contain no artwork.|She prioritizes information after questions reveal omissions.|1,2,3|2
detail|What information does Mr. Cho first ask for?|The arrival time|The river's name|The bakery's address|The artist's age|His Monday question concerns when volunteers should arrive.|1|1
inference|Why does Inez make the river drawing smaller?|To make room for essential instructions.|To hide the cleanup's location.|To remove all references to the river.|To make the lettering harder to see.|The revised layout gives priority to when, where and supplies.|2|2
vocabulary_context|In paragraph 2, crowded most nearly means what?|filled with too many elements|surrounded by shoppers|unpopular with readers|damaged by weather|The poster lacks space because the large drawing dominates it.|2|2
literary|How does Inez's pride change by the end?|She values the poster's usefulness as well as its appearance.|She decides she dislikes all painting.|She insists the first version had no flaws.|She wants the sign-up sheet removed.|She still prefers the first as a picture but keeps the more useful version.|3|3
structure|What purpose do the neighbors' questions serve?|They reveal missing information in the original design.|They prove that the cleanup has been canceled.|They explain how the bakery was built.|They show that the river is unsafe to visit.|The questions expose the missing time and meeting location.|1,2|2
inference|Which observation most directly shows that the second poster communicates clearly?|The child can tell his mother exactly where to go.|The bakery window is large.|Inez spent Saturday painting.|The first drawing uses bright colors.|The child's accurate explanation demonstrates understanding of instructions.|3|2
''')
passage('A Trail of Small Stones','expository',[
'Along a footpath, a row of small stones may seem like decoration. In a restoration project, however, such a row can mark the edge of a newly planted area. It offers a visible reminder to stay on the path while young roots become established. The stones are not a wall; their usefulness depends partly on whether visitors understand them.',
'At one park, volunteers noticed that people repeatedly crossed a planted corner to reach a bench. Adding more stones did little to change the pattern. A volunteer watched the route during several busy afternoons and saw that the shortcut was much more direct than the marked path. The team moved the path slightly and placed a short sign beside the remaining planted area.',
'In the following weeks, fewer footprints appeared among the seedlings. The volunteers could not separate the effect of the new route from the effect of the sign because both changed together. Still, the observations suggested an important lesson: protecting a place can require understanding how people use it, not merely telling them to stop.'
],'''
main_idea|Which statement best captures the passage's point?|Conservation design can improve when it accounts for people's behavior.|Small stones always prevent people from crossing an area.|Signs are the only effective protection for plants.|Visitors use shortcuts only when paths are clearly marked.|The team's observation of use leads to practical changes.|1,2,3|2
detail|Why did visitors cross the planted corner?|It provided a more direct route to a bench.|They had been told to water the plants.|The bench had been removed.|The sign instructed them to cross.|Paragraph 2 identifies the shortcut as more direct.|2|1
inference|Why did adding more stones have little effect?|It did not address the reason people were taking the shortcut.|The stones caused the seedlings to die immediately.|Every visitor failed to see the bench.|The marked path had already been moved.|The behavior continued because the route problem remained.|2|2
vocabulary_context|In paragraph 1, established most nearly means what?|firmly developed|officially announced|carefully counted|recently purchased|The roots need time to develop and take hold.|1|2
structure|Why does the author mention that both the path and sign changed together?|To explain a limit on the conclusion about which change helped.|To prove that neither change could have helped.|To show that the volunteers collected no observations.|To argue that the path should be removed.|The combined change prevents isolating each factor's effect.|3|3
inference|Which conclusion is supported by the observations?|Fewer footprints appeared after the two changes.|The sign alone caused every improvement.|No visitor ever crossed the area again.|The stones were harmful to all roots.|Only the combined before-and-after observation is reported.|3|2
detail|How did the volunteer learn about the shortcut?|By watching the route on several busy afternoons|By interviewing every park visitor|By closing the park for a month|By measuring only the bench's height|Paragraph 2 describes direct observation during busy afternoons.|2|1
''')
passage('The Rehearsal Pause','fiction',[
'During rehearsal, the scene always stumbled at the same place. When Theo entered with the letter, Ada rushed her reply, and the next actor began speaking before she finished. The director stopped them three times. Each time, they tried speaking more loudly, as though volume could untangle the lines.',
'On the fourth attempt, the director asked everyone to stand still after Theo entered. No one was to speak until Ada had looked at the letter. The silence felt enormous. Ada noticed the torn corner of the envelope, then Theo\'s worried face. For the first time, her reply sounded like an answer to what had happened rather than a sentence she had memorized.',
'They tried the scene again without instructions. Theo entered, Ada looked, and the other actor waited. The pause was brief, but the scene no longer hurried past its own surprise. After rehearsal, Ada marked a small dash before her line. She had practiced the words for a week; now she had something to practice between them.'
],'''
main_idea|What does the story suggest about performing a scene?|Listening and reacting can matter as much as speaking the words.|Louder speech always resolves timing problems.|Actors should ignore one another once lines are memorized.|Pauses are useful only when someone forgets a line.|The scene improves when actors attend to events and reactions.|1,2,3|2
detail|What must Ada do before speaking in the new attempt?|Look at the letter|Read the entire letter aloud|Leave the stage|Hand Theo a new envelope|The director's instruction explicitly requires her to look first.|2|1
inference|Why does Ada's reply sound different after the pause?|She responds to details she has actually noticed.|She has replaced every word of her line.|She is trying to shout over Theo.|She has decided the letter is unimportant.|The torn envelope and worried face give her line a reason and emotional context.|2|2
vocabulary_context|In paragraph 1, untangle most nearly means what?|sort out|make longer|speak louder|write down|The metaphor refers to resolving the confused timing of the lines.|1|2
literary|What does the phrase the silence felt enormous convey?|The pause seems unusually noticeable to the actors.|The room physically grows larger.|The actors remain silent for several hours.|The audience has left the building.|Enormous figuratively emphasizes the actors' experience of the pause.|2|3
structure|What is the effect of contrasting words with the space between them at the end?|It emphasizes Ada's new awareness of timing.|It explains that Ada can no longer remember her lines.|It proves the play contains no dialogue.|It shifts the story to a different rehearsal.|The closing contrast summarizes the lesson about meaningful pauses.|3|2
inference|Why does Ada mark a dash before her line?|To remind herself to pause and react before speaking.|To indicate that the line should be shouted.|To cross out the entire scene.|To record the price of the envelope.|The mark follows the successful pause and her recognition of what to practice.|3|2
''')
passage('One Shelf, Many Uses','expository',[
'A neighborhood exchange shelf began with a simple rule: leave a useful item and take one you need. During the first month, the shelf filled with books, jars, and small tools. It also filled with things that could not be used: a cracked mug, a puzzle with missing pieces, and a lamp with a damaged cord. Volunteers spent more time sorting than they had expected.',
'They posted a clearer guide. Items had to be clean, complete, and safe to use. Large objects required a photograph and contact information instead of being left beside the shelf. A notebook invited visitors to request things they needed. Soon a request for measuring cups was answered, while several unwanted decorations remained untouched.',
'The volunteers began reviewing the notebook each week. They did not want the shelf to become merely a place to discard possessions. Its success depended on matching useful items with people who could use them. A smaller, changing collection turned out to serve that purpose better than a larger pile that never moved.'
],'''
main_idea|What is the central idea of the passage?|A successful exchange needs usable items that meet actual needs.|The most successful shelf is always the fullest one.|Every donated object should be accepted without inspection.|Requests make it impossible to organize donations.|Clear standards and attention to requests improve usefulness.|1,2,3|2
detail|How should people offer large objects under the revised guide?|Leave a photograph and contact information.|Place them in front of the shelf.|Break them into smaller pieces.|Put them beside the notebook without a note.|Paragraph 2 gives this specific instruction.|2|1
inference|Why is the measuring-cup request significant?|It shows the notebook helping connect a need with an item.|It proves that only kitchen items are useful.|It shows that decorations are unsafe.|It means visitors must pay for requests.|An actual request is fulfilled, illustrating the notebook's purpose.|2|2
vocabulary_context|In paragraph 3, discard most nearly means what?|get rid of|repair carefully|borrow briefly|display proudly|The volunteers contrast dumping possessions with exchanging useful goods.|3|1
structure|What is the purpose of listing the damaged items in paragraph 1?|To explain why clearer acceptance standards were needed.|To provide instructions for repairing each item.|To show that all donations were worthless.|To suggest that broken goods are especially desirable.|The examples establish the usability problem addressed in paragraph 2.|1,2|2
inference|Which measure would best reflect the volunteers' definition of success?|How often usable items reach people who need them|The total weight of objects left at the shelf|The number of damaged items stored permanently|The amount of floor space covered by donations|The final paragraph defines success in terms of matching items with users.|3|3
detail|What did the volunteers begin reviewing weekly?|The request notebook|The shop's financial ledger|A list of visitors' school grades|The original shelf's purchase receipt|Paragraph 3 says they reviewed the notebook each week.|3|1
''')
