import {sessionTitle,testDuration} from '../domain/testPlan';
import {useState} from 'react';
import type {Session} from '../domain/types';
import {skills,sections} from '../domain/types';
import type {InstalledBank} from '../domain/storage';
import {loadProgress,mergeProgress,resetProgress} from '../domain/storage';
import {parseBackup,type Backup} from '../domain/backup';
import {gradeSession} from '../domain/scoring';
export default function ProgressSettings({view='settings',sessions,installed,status,checking,onCheck,onRefresh,onReview}:{view?:'settings'|'progress';sessions:Session[];installed:InstalledBank|null;status:string;checking:boolean;onCheck:()=>void;onRefresh:()=>Promise<void>;onReview:(s:Session)=>void}){
 const [message,setMessage]=useState('');const [backup,setBackup]=useState<Backup|null>(null);const [reset,setReset]=useState(false);const [busy,setBusy]=useState(false);
 const completed=sessions.filter(s=>s.status!=='active').sort((a,b)=>(b.completedAt??0)-(a.completedAt??0));
 async function task(work:()=>Promise<void>){setBusy(true);try{await work();}catch(e){setMessage(e instanceof Error?e.message:'Could not save changes. Please retry.');}finally{setBusy(false);}}
 const unique=backup?.sessions.filter(s=>!sessions.some(old=>old.id===s.id)).length??0;
 const sectionTotals=new Map<string,{correct:number;total:number}>();for(const s of completed)for(const item of gradeSession(s).items){const key=item.question.section??'quantitative',t=sectionTotals.get(key)??{correct:0,total:0};t.total++;t.correct+=Number(item.outcome==='correct');sectionTotals.set(key,t);}
 const totals=new Map<string,{correct:number;total:number;time:number}>();for(const s of completed)for(const item of gradeSession(s).items){const t=totals.get(item.question.skill)??{correct:0,total:0,time:0};t.total++;t.correct+=Number(item.outcome==='correct');t.time+=s.responses[item.question.id]?.approximateActiveMs??0;totals.set(item.question.skill,t);}
 return <section><h1>{view==='progress'?'Your progress':'Settings'}</h1><p>Progress stays in this browser at this website address. Another browser or device has separate progress. Clearing site data, private browsing, or browser cleanup can remove it. Keep a backup to transfer or recover it.</p>
 {view==='settings'&&<><section className="setup-card"><h2>Question updates</h2><p>{installed?`${installed.manifest.questionCount} questions · Updated ${new Date(installed.manifest.publishedAt).toLocaleDateString()} · ${installed.manifest.releaseId}`:'No saved question bank yet.'}</p><p role="status">{status}</p><button disabled={checking} onClick={onCheck}>{checking?'Checking…':'Check for new questions'}</button><p className="muted">Updates apply to your next practice. Saved tests keep their original questions and answers.</p></section>
 <section className="setup-card settings-section"><h2>Keep your progress</h2><div className="actions"><button disabled={busy} onClick={()=>void task(async()=>{const data=await loadProgress();const url=URL.createObjectURL(new Blob([JSON.stringify({format:'hspt-progress',version:1,exportedAt:new Date().toISOString(),...data},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`hspt-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup downloaded. Keep it somewhere you can find later.');})}>Export progress</button><label className="file-button">Import progress<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void task(async()=>{if(file.size>30_000_000)throw new Error('Backup exceeds 30 MB.');setBackup(parseBackup(await file.text()));setMessage('');});e.target.value='';}}/></label></div>
 {backup&&<div className="notice"><p>Import {unique} new sessions and merge {backup.exposures.length} exposure records. {backup.sessions.length-unique} existing session IDs will be kept unchanged. Questions already encountered remain encountered.</p><button disabled={busy} onClick={()=>void task(async()=>{await mergeProgress(backup.sessions,backup.exposures);setBackup(null);await onRefresh();setMessage('Progress imported. Existing sessions were preserved.');})}>Confirm import</button> <button onClick={()=>setBackup(null)}>Cancel</button></div>}
 <button disabled={busy} onClick={()=>void task(async()=>{const persisted=await navigator.storage?.persist?.();setMessage(persisted?'Persistent storage was granted. A backup is still recommended.':'This browser did not grant persistent storage. Practice still works; keep a backup.');})}>Ask browser to keep progress</button>
 <p role="status">{message}</p><button onClick={()=>setReset(true)}>Reset student progress</button>{reset&&<div className="notice"><p>Delete all sessions, answers, and exposure history in this browser? Your saved question bank will stay installed. Export a backup first if you want to keep your progress.</p><button disabled={busy} onClick={()=>void task(async()=>{await resetProgress();setReset(false);await onRefresh();setMessage('Student progress reset. The question bank is unchanged.');})}>Confirm reset</button> <button onClick={()=>setReset(false)}>Cancel</button></div>}</section>
 </>}
 {view==='progress'&&<><h2 className="settings-section">Practice history</h2>{!completed.length&&<p>No completed practice yet.</p>}<div className="recent-results">{completed.map(s=>{const score=gradeSession(s);return <button key={s.id} onClick={()=>onReview(s)}><span>{new Date(s.startedAt).toLocaleString()} · {sessionTitle(s)}{s.questions.some(q=>q.dummy)?' · Dummy content / provisional score':''}{s.practiceKind==='review'?' · Review set':''}</span><span>{score.completeKey?`${score.correct}/${score.total}`:'Key unavailable'} · {score.attempted} attempted · {Math.round(testDuration(s)/1000)} sec →</span></button>;})}</div>
 {!!sectionTotals.size&&<><h2>By section</h2><p className="muted">Dummy-content scores are provisional. These are practice results, not standardized-test scores.</p><div className="metrics">{[...sectionTotals].map(([section,t])=><p key={section}><strong>{sections[section as keyof typeof sections]}</strong><br/>{t.correct}/{t.total} correct</p>)}</div></>}
 {!!totals.size&&<><h2>By skill</h2><p className="muted">Includes unanswered questions. Attention time is approximate, not exact solving time.</p><div className="metrics">{[...totals].map(([skill,t])=><p key={skill}><strong>{skills[skill as keyof typeof skills]??skill}</strong><br/>{t.correct}/{t.total} correct · {Math.round(t.time/1000)} sec approximate attention across {t.total} questions</p>)}</div></>}
 </>}
 </section>;
}
