from common import setq,passages
TIP='Find evidence in the passage; reject answers that add a claim the text does not support.'
def group(title,genre,paragraphs,rows):
 idx=len(passages)+1;pid=f'passage-a3-{idx:02}'
 passages.append(dict(id=pid,revision=1,title=title,genre=genre,paragraphs=paragraphs,provenance={'origin':'original_agent_authored','date':'2026-09-27'},reviewStatus='pending_human_review'))
 for j,line in enumerate(rows.strip().splitlines()):
  skill,stem,key,a,b,c,why,ev,diff=line.split('|')
  setq('reading',(idx-1)*8+j+1,skill,'passage_'+skill,stem,key,[a,b,c],why,TIP,int(diff),genre+'-'+skill,passageId=pid,passageRevision=1,evidenceParagraphs=list(map(int,ev.split(','))))
 assert j==7

group('The Missing Sound','literary fiction',[
 'The first time Nessa heard her recording of the station, she thought she had made a mistake. The arriving train was there, loud enough to rattle the little speaker. The announcement was there too. But the station she knew had vanished. She had been collecting sounds for a school exhibition called Our Town, and this recording might have belonged to any town at all.',
 'On Saturday she returned before the first train. She held the recorder beside the ticket window, where Mr. Vale was lifting the metal shutter. It caught twice, then sprang upward with a clatter. He laughed. “You will not want that in your exhibition.” Nessa did not answer. From the far bench came the tap of a cane, followed by three notes someone was whistling. Outside, a delivery cart crossed the loose paving stones.',
 'She left these sounds at the beginning of her final recording. At the exhibition, a visitor closed his eyes as the shutter rattled. “I used to buy my ticket there,” he said, before a train had made a sound. Nessa moved the label a little closer to the speaker. She no longer wished she had arrived later.'
],'''
main_idea|Which idea best unifies the story?|Small familiar sounds can give a place its identity.|A clear announcement is essential to a busy station.|Technical practice matters more than choosing a subject.|An exhibition succeeds when it includes famous places.|The first recording lacks identity; the ordinary sounds let a visitor recognize this particular station.|1,2,3|2
detail|When does Nessa make her second recording?|Before the first train arrives.|While the exhibition is opening.|After the last train leaves.|During the loudest announcement.|Paragraph 2 places her return before the first train.|2|1
inference|Why does Nessa keep the shutter's clatter?|It captures a familiar feature of this station.|It hides a problem with the recorder's speaker.|It supports Mr. Vale's opinion of the sound.|It makes the coming train seem unusually quiet.|The visitor recognizes the station from the shutter; Nessa values what Mr. Vale dismisses.|2,3|2
vocabulary_context|In paragraph 1, “vanished” suggests that the station's identity had been what?|Lost from the recording.|Hidden by the visitor.|Removed from the town.|Changed by the exhibition.|The physical station remains; its distinctive character is absent in the first recording.|1|2
structure|What is the main role of the first paragraph?|It establishes a problem that the later visit resolves.|It summarizes what visitors say about the exhibition.|It explains why Mr. Vale objects to being recorded.|It lists the sounds preserved in the final recording.|Nessa's dissatisfaction motivates the second visit and the choice of smaller sounds.|1,2,3|2
literary_interpretation|What does the visitor's recognition show?|The sounds carry a personal memory of the place.|The visitor helped Nessa plan her second recording.|The exhibition has recreated the entire station.|The visitor mistakes the shutter for a train.|His remembered ticket purchase shows that the shutter evokes a particular experience.|3|2
author_purpose|Why does the author mention that Nessa no longer wishes she had arrived later?|To show that she now values the sounds before the train.|To suggest that the early train has been canceled.|To explain why the exhibition closes in the morning.|To reveal that she disliked speaking with Mr. Vale.|Her final attitude reverses the initial focus on the obvious train sound.|1,2,3|3
tone|Which description best fits the ending?|Quietly satisfied.|Sharply resentful.|Playfully mocking.|Nervously apologetic.|Her small adjustment of the label and changed wish convey understated satisfaction.|3|2
''')
group('A Clock That Counts Water','technical explanation',[
 'For a classroom demonstration, a teacher makes a simple timer from a container with a small opening near its bottom. Water flows through the opening into a tray. The class marks the water level on the container after each minute. If the marks were equally far apart, students could use a ruler to add further minute marks without running the timer again. They discover that this shortcut does not work.',
 'The water level falls farther during the first minute than during the fifth. In this setup, water flows out faster when more water stands above the opening. As the level drops, the flow slows. The container has straight sides, so a given change in level represents the same change in volume wherever that change occurs. The unequal spaces between the minute marks therefore reveal a changing flow, not a changing width.',
 'The students can still use their timer. They refill it to the original starting mark and use the marks established by observation. Enlarging the opening would require a new set of marks. So would replacing the straight-sided container with one that narrows at the bottom. Their device measures elapsed time only when its starting conditions and construction match those used to mark it.',
 'One student proposes keeping the upper container filled to a constant level and measuring the water collected below instead. That design would address the falling level, but it would introduce a new practical task: adding water without changing the upper level substantially. The teacher asks the class to build and test the proposal, not to call it an improvement before seeing how it behaves.'
],'''
main_idea|What is the passage mainly explaining?|Why a water timer must be marked and tested under controlled conditions.|Why straight-sided containers prevent changes in water flow.|Why every minute on a timer must occupy an equal distance.|Why collecting water is less reliable than using a clock.|The passage connects changing flow, observed marks and consistent starting conditions.|1,2,3,4|2
detail|Why does the passage specify that the container has straight sides?|Equal changes in level then represent equal changes in volume.|The opening must otherwise be placed above the starting mark.|The container then releases all its water in exactly five minutes.|Its sides make water flow at the same speed throughout the test.|Paragraph 2 explicitly uses the uniform width to rule out container shape as the cause of unequal spacing.|2|2
inference|Which change would require students to mark their original timer again?|Making its outlet opening larger.|Using a different tray that catches all the water.|Watching the timer from the opposite side.|Writing the existing minute labels more clearly.|Paragraph 3 says enlarging the opening requires new marks because it changes the device.|3|2
vocabulary_context|“Elapsed” in paragraph 3 most nearly means what?|Passed.|Predicted.|Remaining.|Repeated.|Elapsed time is the amount of time that has passed.|3|1
structure|How does paragraph 4 develop the discussion?|It considers a proposed solution and a new challenge it creates.|It proves that the original observations were recorded incorrectly.|It replaces the explanation of flow with a historical account.|It shows that the class has abandoned the timer experiment.|The constant-level design addresses one difficulty but needs controlled refilling.|4|2
author_purpose|Why describe the first and fifth minutes?|To provide evidence that the rate of flow changes.|To establish that five minutes is the longest possible test.|To compare the accuracy of two separate containers.|To show when students should stop collecting water.|The unequal falls in level support the explanation of slowing flow.|2|2
evidence|Which observation most directly supports the claim that equal-distance marks would be inaccurate?|The level falls farther in the first minute than in the fifth.|The water leaving the opening is collected in a tray.|The students begin with a straight-sided container.|A student suggests changing how the container is filled.|Unequal level changes during equal time intervals refute equal spacing.|1,2|2
inference|What attitude does the teacher take toward the proposed design?|Promising ideas still need practical testing.|A more complicated device is necessarily more accurate.|A tested design should never be changed.|Keeping the level constant is impossible in practice.|The teacher asks for a build and test before calling the proposal an improvement.|4|3
''')
group('The Two Notices','document comparison',[
 'Notice posted Monday: “The west entrance will close on Wednesday while workers replace its steps. Use the east entrance beside the bicycle rack. Deliveries should arrive before 9 a.m. through the loading door. All classes will meet at their usual times.”',
 'Correction posted Tuesday: “The step replacement has been postponed until Friday. The west entrance will remain open Wednesday and Thursday. On Friday, please use the east entrance. The delivery arrangement announced Monday applies on Friday only. Class times are unchanged.”',
 'A visitor copies the first notice into a calendar on Monday. On Thursday, a receptionist checks the calendar and points out that the visitor has written “classes canceled” beside Friday. The visitor says that the note must have come from one of the notices. The receptionist asks the visitor to read both notices again.'
],'''
main_idea|What is the main effect of Tuesday's correction?|It changes the work date while preserving access and class arrangements.|It moves the classes to another building for the entire week.|It closes both public entrances until workers finish the steps.|It removes all restrictions on deliveries during the repairs.|The correction shifts the work to Friday and keeps the alternative entrance, delivery plan and class times.|1,2|2
detail|Which entrance should a class visitor use on Friday?|The east entrance.|The west entrance.|The loading door.|Either public entrance.|Both notices designate the east entrance during the work; Tuesday places that work on Friday.|1,2|1
inference|Why is the calendar note “classes canceled” unsupported?|Both notices say class times are unchanged.|The receptionist says the workers have already finished.|The first notice mentions no classes at all.|The second notice says the building closes on Thursday.|Neither notice cancels classes; each explicitly preserves their times.|1,2,3|2
vocabulary_context|“Postponed” in paragraph 2 means what?|Moved to a later time.|Finished ahead of time.|Canceled permanently.|Divided into stages.|The work moves from Wednesday to Friday, a later date.|1,2|1
structure|How do the first two paragraphs relate?|The second updates selected details in the first.|The second gives reasons for rejecting every instruction in the first.|The first describes an event that the second says never occurred.|The first is a personal opinion that the second supports with research.|The work date is updated while several arrangements are retained.|1,2|2
evidence|Which detail confirms that the delivery instruction is still relevant?|Tuesday says Monday's delivery arrangement applies on Friday.|Monday says deliveries should arrive before nine in the morning.|Tuesday says the west entrance remains open on Thursday.|Monday directs class visitors to the entrance by the bicycle rack.|Only the explicit carryover on Tuesday establishes its continued relevance on the new date.|2|3
author_purpose|What does the calendar incident illustrate?|A reader must distinguish what a notice says from an assumption.|A handwritten calendar is always less reliable than a printed one.|Visitors should choose entrances without consulting posted notices.|Receptionists are responsible for deciding whether classes will meet.|The cancellation claim is absent from both documents and must be checked against them.|1,2,3|2
inference|Which plan follows the corrected instructions for a Friday delivery?|Arrive before 9 a.m. and use the loading door.|Arrive after 9 a.m. and use the west entrance.|Arrive at any time and use the east entrance.|Arrive before 9 a.m. and use the west entrance.|Tuesday carries Monday's delivery time and loading-door instructions over to Friday.|1,2|2
''')
group('The Seat Beside the Door','literary fiction',[
 'Until the autumn concert, I thought being useful meant being noticed. I played the trumpet, and when a piece offered even four measures of melody, I leaned toward the edge of my chair. My friend Oren played the bass drum. Sometimes he waited through several pages before lifting a beater. I once asked whether he wished he had chosen an instrument with more to do. He looked at his music and said he had plenty to count.',
 'At our final rehearsal, the director asked us to begin halfway through the longest piece. I knew my entrance well enough to play it in my sleep, or so I had told my brother. But from this unfamiliar starting point, the rests before it seemed to multiply. I watched the flutes, then the director, then my own empty measures. Someone behind me turned a page too soon. I came in a measure early, bright and solitary, and stopped so abruptly that the room seemed to keep the unfinished note.',
 'The director corrected the entrance and moved on. During the break I complained to Oren that it was impossible to find my place without hearing the beginning. He laid his part beside mine and pointed to the changes that led toward my entrance: a short line in the clarinets, a pause, then a low phrase in the cellos. He had marked these on his part even though he played nothing there. “I count,” he said, “but I listen too.”',
 'At the concert, my chair stood beside the backstage door. I could hear a hinge complain whenever an usher slipped through. The director lifted her hands. This time I followed the piece through the rests as closely as through my own notes. The clarinets spoke, the cellos answered, and I entered with the other trumpets. A moment later, Oren struck the drum. The sound was brief, exactly where it belonged.',
 'Afterward my brother praised the trumpet melody. I thanked him, but my eyes went toward the rear of the stage, where Oren was covering the drum. I wanted to describe what he had done. “Did you hear—” I began, then hesitated. My brother was already describing another tune. On Monday, I asked Oren if we could look over our new parts together before rehearsal. He pulled out the chair beside him.'
],'''
main_idea|Which theme develops through the narrator's experience?|Musical contribution includes attentive listening as well as audible playing.|Performers learn best when they practice their own parts without others.|A memorable solo can compensate for an inaccurate ensemble performance.|Choosing a quieter instrument prevents embarrassment at rehearsals.|The narrator moves from equating usefulness with notice to valuing Oren's listening and preparation.|1,2,3,4,5|3
detail|What initially causes difficulty at the final rehearsal?|Starting the piece at an unfamiliar midpoint.|A broken hinge interrupting the director.|A missing page in the narrator's music.|Changing the instrument assigned to Oren.|Paragraph 2 says the midpoint start makes the narrator lose track of rests.|2|1
inference|Why has Oren marked passages in which he does not play?|They help him locate his place by listening to other parts.|He intends to play those passages on the trumpet later.|He wants to correct the clarinet players during the concert.|They show the director that his part has too many rests.|He combines counting with audible landmarks, as his explanation states.|3|2
vocabulary_context|“Solitary” in paragraph 2 emphasizes that the note is what?|Alone.|Soft.|Sustained.|Unwritten.|The narrator enters early without the other trumpets; brightness rules out an emphasis on softness.|2|2
structure|What change connects the opening and closing paragraphs?|The narrator shifts from questioning Oren's role to seeking his help.|The narrator replaces a desire to play melody with a desire to leave the band.|Oren changes from avoiding rehearsal to directing it.|The brother learns to prefer the bass drum to the trumpet.|The opening dismissive question contrasts with the final invitation to study together.|1,5|3
literary_interpretation|What does the unfinished “Did you hear—” suggest?|The narrator struggles to explain a contribution the audience may overlook.|The narrator cannot remember which melody the trumpets played.|The brother has asked the narrator to identify a wrong note.|The narrator wants Oren to apologize for a missed entrance.|The narrator now values Oren's contribution but cannot readily communicate it amid praise of the obvious melody.|4,5|3
evidence|Which action most clearly demonstrates the narrator's lasting change?|Asking Oren to examine the next set of parts together.|Thanking the brother for praising the melody.|Watching the director during the final rehearsal.|Stopping immediately after the early entrance.|Seeking Oren's perspective for new music goes beyond simply correcting one mistake.|5|2
tone|How is the narrator's earlier attitude presented?|With reflective self-criticism.|With bitter blame toward the director.|With unqualified pride in solo ability.|With amused contempt for the audience.|The retrospective opening and account of overconfidence acknowledge the narrator's own mistaken view.|1,2,5|3
''')
group('When a Blank Is Information','expository',[
 'A neighborhood archive contains a ledger listing the tools lent by a repair club. Most entries record a borrower’s name, a date, and the returned tool. For one week in April, the return column is blank. An early description of the ledger called this “the week nobody returned anything.” A student preparing a new exhibit wondered whether the blank could support so confident a claim.',
 'She compared the ledger with a box of separate receipts. Several receipts showed tools returned during that week. She also found a note explaining that the club had moved its desk to another room while the floor was repaired. Perhaps the ledger had not been kept at the temporary desk. That explanation fit the evidence, but the note did not say where the ledger had been. The student therefore did not present the explanation as a fact.',
 'Her exhibit label read: “Return entries are missing for this week. Separate receipts show that some tools did come back. The move during floor repairs may explain the gap.” The new label was longer than the old one. It also asked more of the visitor: instead of offering a simple story, it separated an observation, evidence against one interpretation, and a possible explanation.',
 'The student did not conclude that records were useless. The ledger still contained information unavailable elsewhere, and the receipts were incomplete too. Each source helped test claims made from the other. A blank was a reason to investigate the recording process, not an automatic sign that nothing had happened.'
],'''
main_idea|What is the central lesson of the passage?|Missing entries must be interpreted in light of how records were kept.|Separate receipts are always more accurate than a bound ledger.|An exhibit should replace uncertain explanations with a single story.|A complete archive must record every event in more than one place.|The receipts contradict the initial inference, while the desk move offers only a tentative explanation.|1,2,3,4|2
detail|What evidence contradicts “nobody returned anything”?|Receipts showing returns during the blank week.|A note describing repairs to the club's floor.|The ledger's usual use of three kinds of entries.|The student's decision to write a longer label.|The receipts directly establish some returns; the floor note alone does not.|1,2|1
inference|Why does the student use “may” in the label?|The desk move is a plausible explanation that is not confirmed.|The receipts fail to show whether any tools came back.|The ledger records that the desk never moved.|The exhibit must avoid mentioning definite dates.|The note confirms a move, not its effect on ledger use.|2,3|2
vocabulary_context|“Gap” in paragraph 3 refers to what?|The missing return entries.|The distance between the rooms.|The space left on the exhibit wall.|The interval between two floor repairs.|The label is discussing the absent week's entries.|1,3|1
structure|What purpose does the final paragraph serve?|It prevents the case from being taken as a reason to reject records altogether.|It introduces proof that the student's proposed explanation is correct.|It lists the steps needed to repair the damaged floor.|It argues that a shorter label would have been more useful.|It explicitly qualifies the lesson: sources remain useful and can test one another.|4|2
author_purpose|Why quote both the old description and the new label?|To contrast an unsupported conclusion with a carefully limited account.|To show that visitors prefer longer descriptions of familiar tools.|To prove that students write more vividly than professional archivists.|To compare two eyewitness accounts of a single return.|The quoted texts expose different degrees of certainty based on evidence.|1,3|2
evidence|Which statement best supports the claim that neither source is sufficient by itself?|The ledger has unique information, and the receipts are incomplete.|Most ledger entries include a borrower's name and a date.|The student prepares a label for a neighborhood exhibit.|The desk moves while the club's floor is being repaired.|The final paragraph describes both complementary value and limitations.|4|2
inference|Which discovery would most strengthen the student's tentative explanation?|A dated instruction to leave the ledger unused during the desk move.|A list of tools purchased several years before the blank week.|A photograph of the repaired floor taken after the club closed.|A receipt confirming a return already documented in the box.|An instruction linking nonuse of the ledger to the move would support the proposed cause.|2,3|3
''')
group('A Longer Lunch Line?','argument',[
 'The student council proposes opening a second lunch counter. Opponents point out that the dining room already has empty seats. But seats and counters solve different problems. A seat helps a student who has food; a counter serves a student still waiting to receive it. Empty seats alone do not show that the serving system works well.',
 'Before buying equipment, the school should measure where students wait. For a week, observers could record the time students join the line, receive food, and find a seat. They should include busy and quiet days. If most delay occurs before students reach the counter, a second serving point may help. If the slowest step is payment and both counters lead to the same cashier, the purchase may merely produce two lines that stop in the same place.',
 'A temporary second serving table would let the school test the idea without making a permanent commitment. The trial should keep staffing and the menu as comparable as possible and record any unavoidable changes. A faster line on pizza day cannot fairly be compared with a slower line on a day when every meal requires several separate choices.',
 'This proposal is not an argument for postponing improvement indefinitely. It is an argument for buying the improvement students actually need. A week spent finding the delay may save a school from years of owning an expensive answer to the wrong question.'
],'''
main_idea|Which statement best expresses the author's position?|Identify and test the source of delay before buying a second counter.|Buy another counter as soon as students report a long line.|Use the number of empty seats to decide whether lunch is efficient.|Reject additional equipment because the menu controls all waiting time.|The author favors measurement and a trial to target the actual cause.|1,2,3,4|2
detail|What three times would observers record?|Joining the line, receiving food, and finding a seat.|Opening the kitchen, preparing food, and washing dishes.|Arriving at school, starting lunch, and leaving school.|Ordering equipment, delivering it, and installing it.|Paragraph 2 explicitly names the three stages.|2|1
inference|Why might a second counter fail to reduce waiting?|Both lines could still depend on one slow cashier.|More serving space would necessarily reduce the number of seats.|Students would always choose the original counter.|An additional counter would prevent observers from measuring time.|The shared payment bottleneck could remain unchanged.|2|2
vocabulary_context|“Commitment” in paragraph 3 most nearly means what?|A lasting investment.|A spoken complaint.|A daily assignment.|A measured delay.|The temporary table avoids committing permanently to equipment and arrangements.|3|2
structure|What does the final paragraph do?|It answers a possible objection that testing would only delay useful action.|It introduces a new claim that the lunch schedule should be shortened.|It withdraws the proposed trial in favor of an immediate purchase.|It summarizes results already obtained from the experiment.|The author explicitly rejects indefinite postponement and explains the purpose of testing.|4|3
author_purpose|Why contrast pizza day with a day offering separate choices?|To show how menu differences could distort a comparison.|To argue that students should be allowed only one menu.|To show that pizza requires more staff than other meals.|To prove that equipment purchases cannot change waiting times.|Different meal-selection demands could confound a test of the second table.|3|2
evidence|Which detail most directly challenges the opponents' use of empty seats?|A seat serves someone with food; a counter serves someone still waiting for it.|Observers should measure both busy and quiet days during the week.|A temporary table could be used before equipment is purchased.|The school should record changes that cannot be avoided during the trial.|The distinction explains why vacant seats do not resolve a serving-line delay.|1|2
tone|Which pair best describes the author's tone?|Practical and persuasive.|Nostalgic and regretful.|Sarcastic and dismissive.|Celebratory and certain.|The author advocates concrete testing while acknowledging several possible outcomes.|1,2,3,4|2
''')
group('The Mapmaker’s Margin','literary fiction',[
 'Eli had promised a clean map of the island for the visitors arriving on Sunday. He ruled a border around a fresh sheet and copied the shoreline from the old survey. Then he filled the center with roads, houses, and the names of the three hills. The map looked finished until his aunt asked where the spring path began. Eli pointed to a neat line near the orchard. “That is where the survey puts it,” he said.',
 'They walked there after lunch. The line on his paper became a tangle of nettles on the ground. Beyond it, a narrow trail curved around a fallen tree and joined the path farther uphill. His aunt waited while he sketched the turn on the back of an envelope. “Will you erase the old route?” she asked. Eli said yes, then stopped. He could change the line, but he did not know whether the fallen tree would be cleared next week. A visitor coming later might need a different map.',
 'Back at the table he added a date and wrote, “Temporary detour around fallen tree.” The words would not fit inside his carefully ruled border. He could shrink them until they looked like a trail of ants, or move the border. He moved it. Soon the new margin held another note: “Steps near the jetty are slippery after rain.” The sheet was less elegant than it had been that morning.',
 'On Sunday a visitor studied the notes before choosing a walk. She folded the map along a crease Eli had tried to keep out of the lettering and tucked it into her pocket. He nearly offered her an uncreased copy. Instead, he asked whether the spring path had been easy to find. When she returned that afternoon, there was a small pencil correction beside the jetty. The handrail was loose as well. Eli thanked her and reached for the next sheet.'
],'''
main_idea|What does Eli come to understand about a useful map?|It must communicate changing conditions as well as a tidy arrangement.|It should preserve an old survey even when the ground has changed.|It becomes less reliable whenever someone writes in its margin.|It is finished once the shoreline and road names are correct.|Dates, detours, cautions and the visitor's correction improve practical usefulness.|1,2,3,4|2
detail|Why does Eli describe the detour as temporary?|He does not know whether the fallen tree will soon be cleared.|His aunt asks him to remove every permanent path from the map.|The survey labels all routes on the island as temporary.|Visitors are permitted to use the detour only on Sunday.|Paragraph 2 explains his uncertainty about how long the obstruction will remain.|2,3|2
inference|Why does Eli move the border rather than shrink the note?|Readable information has become more important than the original layout.|He plans to leave the map mostly empty for visitors to complete.|He wants the island to appear larger than the old survey shows.|He has discovered that small writing is prohibited on public maps.|The choice sacrifices elegance to keep the practical note readable.|3|2
vocabulary_context|The phrase “a trail of ants” describes what quality of the smaller words?|Their tiny appearance.|Their unreliable meaning.|Their irregular spelling.|Their rapid disappearance.|The simile refers to the visual effect of shrinking lettering too far.|3|2
structure|How does the visitor's correction extend the earlier detour episode?|It shows that useful revisions continue after the map is handed out.|It proves the first correction should never have been included.|It explains why Eli's aunt prefers the old survey.|It resolves the uncertainty about when the tree will be removed.|The loose handrail gives new information for the next copy, continuing the revision process.|2,4|3
literary_interpretation|What is suggested by Eli's decision not to offer an uncreased copy?|He accepts signs of use instead of insisting on a pristine object.|He has run out of paper for making another map.|He believes the visitor has deliberately damaged his work.|He wants to hide the wording in the map's margin.|The moment reflects his shift away from valuing appearance above function.|1,3,4|3
evidence|Which action best shows that Eli welcomes further revision?|He thanks the visitor and reaches for the next sheet.|He copies the shoreline from the old survey.|He rules a border around a fresh sheet.|He points to the route near the orchard.|The final action responds constructively to new information.|4|1
tone|How does the ending present Eli's work?|As useful work that remains open to improvement.|As an unsuccessful task he is relieved to abandon.|As a private achievement visitors fail to appreciate.|As a contest he has won against his aunt.|He continues making the next version after receiving helpful feedback.|4|2
''')
group('Two Ways to Report a Race','quantitative exposition',[
 'Five teams enter a relay and finish at different times. A notice reports only that Team Cedar finishes third. That statement gives Cedar a position but not a finishing time. Cedar could be a fraction of a second behind the winner or several minutes behind. Rank alone cannot reveal the gap.',
 'A second notice lists each team’s time. It allows readers to calculate gaps as well as determine order. Yet times also need context. If next year’s relay uses a longer course, a slower finishing time would not by itself prove that a team performed worse. Comparing performances requires attention to the conditions being compared.',
 'Rank and time therefore answer different questions. A coach asking “Whom did we finish ahead of?” needs the order. A coach asking “How much time separated us from the winner?” needs the times. Neither measure is useless; the mistake is expecting one to provide information it does not contain.'
],'''
main_idea|What is the main point of the passage?|A measure is useful when it matches the question being asked.|A finishing time is always more informative than every other measure.|A team's rank reliably shows whether its performance has improved.|A relay result cannot be compared with any other result.|The passage distinguishes what order and time can each establish.|1,2,3|2
detail|What does the first notice establish about Cedar?|Its finishing position among the five teams.|Its exact distance behind the winning team.|Its finishing time on the relay course.|Its improvement since the previous year.|Third place reports order, not time, gap or change across years.|1|1
inference|Which conclusion is justified from third place alone?|Two teams finished ahead of Cedar.|Cedar finished within one second of second place.|Cedar ran more slowly than it did last year.|The winning team broke a course record.|Third place among five entails two ahead; no times or past results are given.|1|2
vocabulary_context|“Context” in paragraph 2 refers most nearly to what?|The surrounding conditions relevant to a result.|The decorative design surrounding a race notice.|The spectators' preferred account of the race.|The order in which coaches read the report.|The example identifies course length as a condition needed for fair interpretation.|2|2
structure|What is the function of the longer-course example?|It limits what a comparison of raw times can establish.|It explains why rank must be printed before time.|It proves that all teams improve on longer courses.|It introduces a new way of assigning finishing positions.|Changed course length can explain a slower time, so raw times alone do not settle performance change.|2|2
author_purpose|Why include two questions a coach might ask?|To illustrate different information needs.|To recommend that coaches avoid calculating time gaps.|To demonstrate that the notices contradict each other.|To show which team the author wants to win.|Each question calls for a different measure.|3|1
evidence|Which statement supports the claim that third place does not reveal the time gap?|Cedar might be a fraction of a second or several minutes behind.|There are five teams entered in the relay.|The second notice lists every team's finishing time.|A longer course may be used the following year.|Two very different possible gaps are compatible with the same rank.|1|2
inference|Which comparison would best address improvement in a team's speed?|Its times over the same distance under comparable conditions.|Its ranks in races with different opponents and course lengths.|Its third-place finish compared with another team's third place.|Its finishing order without any record of elapsed time.|The passage calls for comparable conditions; equal distances and recorded times support a speed comparison.|2,3|3
''')
# Standalone vocabulary: distinct targets absent from the reference transcription and other local target lists.
rows='''
reticent|reserved|resentful|resolute|restless|Reticent describes reluctance to speak freely; reserved is closest.|2
judicious|sensible|judgmental|generous|hasty|Judicious means showing sound judgment, not merely making judgments about others.|2
austere|plain|outdated|delicate|gloomy|Austere can describe a severely plain style with little decoration.|3
elusive|evasive|obvious|fragile|imaginary|Elusive means hard to catch or pin down; evasive is closest among these choices.|2
cumbersome|unwieldy|massive|intricate|costly|Cumbersome means awkward to handle; weight or complexity alone does not define it.|2
fervent|passionate|impatient|anxious|stubborn|Fervent means intensely earnest or passionate.|2
prudent|sensible|timid|shrewdly dishonest|indecisive|Prudent means showing sound, careful judgment; it does not require fear or dishonesty.|2
venerable|respected|vulnerable|fashionable|energetic|Venerable means deserving respect, often because of age or character.|3
succinct|brief|abrupt|incomplete|indirect|Succinct means expressed briefly and clearly; abrupt can describe manner without clarity.|2
tenable|defensible|temporary|flexible|compulsory|A tenable position can be maintained or defended against challenge.|3
dissonant|discordant|distant|rhythmic|faint|Dissonant describes sounds that clash rather than harmonize.|3
unassuming|modest|uncertain|inexperienced|unprepared|Unassuming means not drawing attention to one's importance, rather than lacking confidence or preparation.|2
susceptible|vulnerable|suspicious|resistant|unaware|Susceptible means liable to be affected; vulnerable is closest.|2
transient|temporary|transparent|unusual|recurrent|Transient means lasting only a short time.|2
parsimonious|stingy|thrifty but generous|careless|impoverished|Parsimonious suggests excessive unwillingness to spend; it does not simply mean poor.|3
equivocal|ambiguous|balanced|unmistakable|irrelevant|Equivocal language permits more than one interpretation; balance or irrelevance is different.|3
unerring|accurate|unyielding|unhurried|unfamiliar|Unerring means not making mistakes, so accurate is closest.|2
prosaic|ordinary|poetic|lengthy|formal|Prosaic means commonplace or unremarkable, not merely written in prose.|3
fortuitous|accidental|profitable|inevitable|carefully planned|Fortuitous means happening by chance; a chance event need not be profitable.|3
precarious|insecure|precise|remote|valuable|Precarious describes something unstable or insecure.|2
placid|calm|dull|secretive|rigid|Placid means calm or undisturbed, not necessarily uninteresting.|2
assiduous|diligent|ambitious|obedient|gifted|Assiduous means showing persistent care and effort, whether or not one is talented or ambitious.|3
sagacious|wise|elderly|talkative|fortunate|Sagacious means possessing keen judgment; age alone does not establish it.|3
tacit|unspoken|secret|unclear|incomplete|Tacit means understood without being directly stated; it need not be secret or unclear.|3
innocuous|harmless|ineffective|unnoticed|unusual|Innocuous means not harmful; something can be noticeable and still innocuous.|2
magnanimous|generous|extravagant|famous|powerful|Magnanimous means generous in spirit, especially toward an opponent.|3
indelible|permanent|invisible|illegible|colorful|An indelible mark cannot readily be removed; permanent is closest.|2
fallacious|unsound|unpopular|unfinished|unfamiliar|Fallacious reasoning is based on error, not merely disagreement or unfamiliarity.|3
impervious|impenetrable|indestructible|invisible|inflexible|Impervious means not allowing passage or being unaffected; impenetrable is the closest offered meaning.|3
perfunctory|mechanical|thorough|prompt|compulsory|Perfunctory work is done routinely with little care or interest; speed or obligation alone does not define it.|3
vindicate|justify|avenge|praise|forgive|To vindicate is to clear from blame or show to be justified; forgiveness can leave blame intact.|3
emulate|imitate|admire|surpass|criticize|To emulate is to imitate with an aim of matching another; success in surpassing is not required.|2
stipulate|specify|suggest|negotiate|infer|To stipulate is to specify a requirement or condition.|3
corroborate|confirm|repeat|explain|question|To corroborate is to support or confirm with evidence, not merely repeat a claim.|3
exonerate|absolve|excuse casually|reward|forget|To exonerate is to clear of blame or responsibility; absolve is closest.|3
expedite|hasten|organize|complete|postpone|To expedite is to speed up a process; completion is not implied.|2
'''
for j,line in enumerate(rows.strip().splitlines(),65):
 word,key,a,b,c,why,diff=line.split('|')
 setq('reading',j,'standalone_vocabulary','standalone_vocabulary',f'Which word or phrase is closest in meaning to {word.upper()}?',key,[a,b,c],why,'Choose the closest meaning, not merely a related idea or a similar-looking word.',int(diff),'reading-vocabulary-'+word,targetWord=word)
