"""Author a staged revision; never modify the live bank or approve content."""
import json,copy,random
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'content/staging/gables-v2'
old=json.loads((ROOT/'content/imports/current-100.json').read_text())
BANK=[];PROOFS={};CHANGES=[]
POSITIONS=list(range(4))*25
random.Random("gables-v2-positions").shuffle(POSITIONS)
def append(q,proof,origin=None):
 q=copy.deepcopy(q);q['id']=f'gb2-{len(BANK)+1:03}'
 q.update(section='quantitative',reviewStatus='pending_human_review',sourceType='original_draft',bankVersion='gables-v2',provenance={'origin':'original AI-assisted authorship','priorId':origin,'referenceUse':'format calibration only'})
 # Rotate independently of source choices; use each key position 25 times.
 choices=q['choices'];answer=choices['ABCD'.index(q['guide']['correctChoiceId'])];target=POSITIONS[len(BANK)];shift=(choices.index(answer)-target)%4
 q['choices']=choices[shift:]+choices[:shift];q['guide']['correctChoiceId']='ABCD'[target]
 proof=copy.deepcopy(proof)
 if proof['kind']=='relations':proof['predicates']=proof['predicates'][shift:]+proof['predicates'][:shift]
 q['answerFormat']=q.get('answerFormat','numeric');BANK.append(q);PROOFS[q['id']]=proof
 CHANGES.append({'id':q['id'],'priorId':origin,'action':'retained/rechecked' if origin else 'new original item'})
 return q

def new(skill,fmt,family,d,stem,choices,answer,explanation,tip,proof,visual=None,answerFormat='numeric',origin=None):
 choices=choices.split('|') if isinstance(choices,str) else choices
 q={'skill':skill,'format':fmt,'templateFamily':family,'difficulty':d,'stem':stem,'choices':choices,'guide':{'correctChoiceId':'ABCD'[choices.index(answer)],'explanation':explanation,'shortcut':tip},'answerFormat':answerFormat}
 if visual:q['visual']=visual
 return append(q,proof,origin)
# Validation rules below were derived from the supplied terms, not answer letters.
sequence_rules={
'dev-01':('cycle',[5]),'dev-02':('gaps',[3,1]),'dev-09':('multiply','1/2'),
'quant-013':('cycle',[-7]),'quant-014':('cycle',['2/5']),'quant-015':('gaps',[2,2]),'quant-016':('gaps',[-11,1]),'quant-017':('cycle',[3,5]),'quant-018':('branches',[3,-2]),'quant-019':('cycle',['1/2']),'quant-020':('cycle',[9]),'quant-021':('gaps',[3,2]),'quant-022':('gaps',[-2,-2]),'quant-023':('cycle',[7,-4]),'quant-024':('sum_previous',[]),'quant-026':('gaps',[9,-1]),'quant-027':('cycle',[5]),'quant-028':('cycle',[2,3,4]),
'quant-029':('multiply',3),'quant-030':('multiply','1/3'),'quant-031':('affine',[2,1]),'quant-032':('affine',[3,-1]),'quant-033':('multiply','1/2'),'quant-034':('multiply_cycle',[2,3]),'quant-035':('rising_multiply',2),'quant-036':('multiply',10),'quant-037':('multiply',4),'quant-039':('multiply','3/2'),'quant-042':('multiply_branches',[2,3])}
replacements={'dev-03','quant-025','quant-038','quant-040','quant-041'}
import re
for q in [q for q in old if q['skill'].startswith('sequence_')]:
 prior=q['id']
 if prior in replacements:
  if prior=='dev-03':
   new('sequence_multiplicative','number_series','triple-and-decrement',2,'Which pair continues the sequence?  9, 27, 26, 78, 77, …','230, 231|231, 230|231, 232|154, 153','231, 230','The steps alternate ×3 and −1. After 77, multiply by 3 to get 231, then subtract 1 to get 230.','Check both requested terms; a pair can start correctly and still finish incorrectly.',{'kind':'series','terms':[9,27,26,78,77],'rule':'op_cycle','params':[['mul',3],['add',-1]],'output':2},answerFormat='numeric_pair')
  elif prior=='quant-025':
   new('sequence_additive','number_series','paired-gap-blocks',2,'What number fills the blank?  3, 7, 11, 18, 25, __, 45','29|32|35|38','35','The differences come in pairs: +4, +4, then +7, +7, then +10, +10. The missing value is 25 + 10 = 35; 35 + 10 = 45.','Use the term after a blank to check your proposed rule.',{'kind':'series','terms':[3,7,11,18,25,None,45],'rule':'paired_gaps','params':[4,3]})
  elif prior=='quant-038':
   new('sequence_multiplicative','number_series','halving-and-counting-branches',3,'Which pair continues the sequence?  96, 5, 48, 7, 24, 9, …','12, 10|12, 11|18, 11|48, 7','12, 11','The odd-position terms halve: 96, 48, 24, 12. The even-position terms increase by 2: 5, 7, 9, 11. The next pair is 12, 11.','Separate odd and even positions before trying a rule for every adjacent pair.',{'kind':'series','terms':[96,5,48,7,24,9],'rule':'mixed_branches','params':['1/2',2],'output':2},answerFormat='numeric_pair')
  elif prior=='quant-040':
   new('sequence_multiplicative','number_series','descending-letters-square-counts',3,'What term comes next?  M1, K4, I9, …','G12|H16|G16|F25','G16','The letters move backward two places: M, K, I, G. The numbers are consecutive squares: 1, 4, 9, 16. Combine the next letter and number to get G16.','Check the letter and number rules separately before joining them.',{'kind':'alphanumeric','terms':['M1','K4','I9'],'letterStep':-2,'numberRule':'squares'},answerFormat='alphanumeric')
  else:
   new('sequence_multiplicative','number_series','cube-offset',3,'What number comes next?  2, 9, 28, 65, 126, …','180|196|216|217','217','The terms are one more than consecutive cubes: 1³ + 1, 2³ + 1, 3³ + 1, 4³ + 1, and 5³ + 1. The next is 6³ + 1 = 217.','Check familiar powers when simple differences and ratios do not fit.',{'kind':'series','terms':[2,9,28,65,126],'rule':'cube_plus_one','params':[]})
  CHANGES[-1].update(priorId=prior,action='replaced: source overlap or scaffolded format')
 else:
  q=copy.deepcopy(q);q['format']='number_series'
  rule,param=sequence_rules[prior]
  raw=q['stem'].split('?')[-1] if '?' in q['stem'] else q['stem']
  # The original series stems contain no other numeric quantities.
  terms=[None if t.strip()=='__' else t.strip().replace('−','-') for t in raw.replace('…','').strip(' .').split(',') if t.strip()]
  append(q,{'kind':'series','terms':terms,'rule':rule,'params':param},prior)
assert len(BANK)==34
# Existing manipulations remain useful, with fresh independent expression checks.
exprs={'dev-05':'84/4','dev-08':'(35-9)/2','quant-059':'350/10','quant-060':'80*15/100','quant-061':'18/(30/100)','quant-062':'40*(1-20/100)','quant-063':'35*3/5','quant-064':'15*3-12-16','quant-065':'7+3*8','quant-066':'19*6','quant-067':'64*3/8','quant-068':'15/5*8','quant-069':'72/3+1','quant-070':'157%6','quant-071':'52/4','quant-072':'(46+8)/2','quant-073':'(50-40)/40','quant-074':'3/4/2'}
for q in [q for q in old if q['skill']=='number_manipulation']:
 q=copy.deepcopy(q);q['format']='number_manipulation'
 if q['id'] in {'quant-071','quant-074'}:q['difficulty']=2
 append(q,{'kind':'numeric','expression':exprs[q['id']]},q['id'])

def manipulation(family,d,stem,opts,answer,expr,explanation,tip):
 return new('number_manipulation','number_manipulation',family,d,stem,opts,answer,explanation,tip,{'kind':'numeric','expression':expr})
manipulation('fractional-remainder',2,'A ribbon is 72 cm long. After 1/3 is cut away, the remaining ribbon is divided into 4 equal pieces. How long is each piece, in cm?','6|12|16|18','12','(72-72/3)/4','One third of 72 is 24, leaving 48 cm. Divide 48 by 4 to get 12 cm per piece.','Find what remains before dividing it into pieces.')
manipulation('target-balance',2,'A balance starts at 18 points. Each correct answer adds 5 points and each incorrect answer removes 2. After 4 correct and 3 incorrect answers, what is the balance?','26|30|32|38','32','18+4*5-3*2','Four correct answers add 20 points; three incorrect answers remove 6. The final balance is 18 + 20 − 6 = 32.','Compute gains and losses separately, then combine them.')
manipulation('repeated-discount-amount',2,'A $60 item is reduced by 10%, then reduced by another $6. What is its final price in dollars?','42|48|50|54','48','60*9/10-6','A 10% reduction removes $6, leaving $54. The additional $6 reduction leaves $48.','A dollar reduction and a percentage reduction are different operations.')
manipulation('weighted-mean',3,'Two quiz scores average 14 points. A third score raises the average of all three to 16. What is the third score?','16|18|20|22','20','3*16-2*14','The first two scores total 28. All three must total 48, so the third score is 48 − 28 = 20.','Convert both averages to totals before subtracting.')
manipulation('ratio-transfer',1,'A box has 12 red and 20 blue tokens. How many blue tokens must be removed so that red and blue tokens are equally numerous?','4|8|12|16','8','20-12','Keep the 12 red tokens and reduce the blue count to 12. Remove 20 − 12 = 8 blue tokens.','Only the named group changes; do not split the difference between groups.')
manipulation('inverse-fraction-step',2,'After 6 is added to a number, the result is divided by 3 to give 11. What is the original number?','9|17|27|39','27','11*3-6','Before division the value was 11 × 3 = 33. Before adding 6 it was 33 − 6 = 27.','Undo the steps in reverse order.')
manipulation('unit-conversion-remainder',2,'A 2-metre cord is cut into five 30-cm lengths. How many centimetres remain?','20|30|50|150','50','2*100-5*30','Two metres is 200 cm. Five pieces use 150 cm, leaving 50 cm.','Convert to one unit before subtracting.')
manipulation('difference-of-squares',2,'How much greater is the square of 9 than the square of 7?','4|16|32|64','32','9**2-7**2','The squares are 81 and 49. Their difference is 32.','You can also use (9 − 7)(9 + 7) = 2 × 16.')
manipulation('fraction-missing-sum',2,'What fraction must be added to 5/12 to make 3/4?','1/6|1/4|1/3|2/3','1/3','3/4-5/12','Three quarters is 9/12. Subtract 5/12 to get 4/12, which simplifies to 1/3.','Use a common denominator before finding the missing part.')
manipulation('discrete-capacity',2,'A tray holds 8 cups. What is the smallest number of trays needed to hold 35 cups?','4|5|6|7','5','(35+7)//8','Four trays hold only 32 cups. One more tray is needed for the remaining 3 cups, so 5 trays are required.','A partially filled final tray still counts as a whole tray.')
manipulation('double-and-half-percent',2,'A number is increased by 50% and becomes 42. What was the number?','21|28|30|63','28','42/(3/2)','The new value is 1.5 times the original. Divide 42 by 1.5 to get 28; half of 28 is 14, and 28 + 14 = 42.','Treat the result as three half-sized parts; the original is two of those parts.')
manipulation('equal-groups-change',3,'Six equal groups contain 54 counters altogether. Two groups are removed, then 7 counters are added. How many counters are there now?','25|34|36|43','43','54/6*4+7','Each group contains 9 counters. Four groups remain, containing 36; adding 7 gives 43.','Find one group, then rebuild only the groups that remain.')
manipulation('consecutive-odd-total',3,'Three consecutive odd numbers total 87. What is the smallest?','25|27|29|31','27','87/3-2','The middle number is 87 ÷ 3 = 29. Consecutive odd numbers differ by 2, so the smallest is 27.','The middle value equals the average for three equally spaced numbers.')
manipulation('rate-with-fixed-part',2,'A delivery charge is $4 plus $3 for each parcel. The total charge is $25. How many parcels were delivered?','6|7|8|9','7','(25-4)/3','Remove the fixed $4 charge: 25 − 4 = 21. Divide by $3 per parcel to get 7 parcels.','Subtract the fixed amount before dividing by the per-item amount.')
assert len(BANK)==66
# Relations are explicit predicates: the checker evaluates all four alternatives.
def relation(family,d,definitions,values,opts,predicates,answer,explanation,tip):
 q=new('numeric_comparison','nongeometric_comparison',family,d,'Compare the quantities. Which statement is true?\n'+definitions,opts,answer,explanation,tip,{'kind':'relations','values':values,'predicates':predicates},answerFormat='relationship')
 return q
relation('fraction-percent-equality',2,'P = 3/8 of 80; Q = 35% of 80; R = 0.3 × 100.',{'P':'3/8*80','Q':'35/100*80','R':'3/10*100'},['P = Q','Q > R','P = R > Q','P < Q < R'],['P==Q','Q>R','P==R and R>Q','P<Q and Q<R'],'P = R > Q','P = 30, Q = 28, and R = 30. Therefore P and R are equal and both exceed Q.','Find a common quantity before comparing different representations.')
relation('negative-order',2,'P = −3 × 4; Q = 5 − 14; R = −2 × 5.',{'P':'-3*4','Q':'5-14','R':'-2*5'},['P > Q > R','Q > R > P','R > P > Q','P = R'],['P>Q and Q>R','Q>R and R>P','R>P and P>Q','P==R'],'Q > R > P','P = −12, Q = −9, and R = −10. Among negatives, the number closer to zero is greater.','Place negative values on a mental number line.')
relation('operation-grouping',2,'P = 4 × (9 − 2); Q = 4 × 9 − 2; R = 4 × 9 − 4 × 2.',{'P':'4*(9-2)','Q':'4*9-2','R':'4*9-4*2'},['P = Q = R','P = R < Q','P > R','Q < R'],['P==Q and Q==R','P==R and R<Q','P>R','Q<R'],'P = R < Q','P and R both equal 28 by the distributive property. Q equals 34 because only 2 is subtracted.','Distribute a multiplier to every term inside parentheses.')
relation('fraction-near-one',2,'P = 11/12; Q = 7/8; R = 5/6.',{'P':'11/12','Q':'7/8','R':'5/6'},['P > Q > R','Q > P > R','R > Q > P','P = Q'],['P>Q and Q>R','Q>P and P>R','R>Q and Q>P','P==Q'],'P > Q > R','Their gaps below 1 are 1/12, 1/8, and 1/6. The smallest gap belongs to the greatest fraction.','Compare distances below 1 rather than dividing all three fractions.')
relation('ratio-decimal-order',2,'P = 7 ÷ 20; Q = 0.305; R = 33%.',{'P':'7/20','Q':'305/1000','R':'33/100'},['Q > P','P < R','P > R > Q','P = R'],['Q>P','P<R','P>R and R>Q','P==R'],'P > R > Q','P is 0.35, R is 0.33, and Q is 0.305. Thus P > R > Q.','Write each value to the same decimal precision.')
relation('two-quantity-sum',2,'P = 2³; Q = 3²; R = 4².',{'P':'2**3','Q':'3**2','R':'4**2'},['P + Q = R','P + Q > R','P > Q','R < Q'],['P+Q==R','P+Q>R','P>Q','R<Q'],'P + Q > R','P = 8, Q = 9, and R = 16. Their sum P + Q is 17, which is greater than 16.','Evaluate the requested relationship, not only the largest single quantity.')
relation('percentage-complement',2,'P = 60% of 45; Q = 40% of 45; R = 9.',{'P':'60/100*45','Q':'40/100*45','R':'9'},['P − Q = R','P + R = Q','Q = R','P = Q'],['P-Q==R','P+R==Q','Q==R','P==Q'],'P − Q = R','P is 27 and Q is 18. Their difference is 9, equal to R.','The difference between 60% and 40% is 20% of the same base.')
relation('reciprocal-size',2,'P = 1 ÷ 0.25; Q = 1 ÷ 0.5; R = 1 ÷ 2.',{'P':'1/(1/4)','Q':'1/(1/2)','R':'1/2'},['P < Q < R','P = Q','P > Q > R','R > P'],['P<Q and Q<R','P==Q','P>Q and Q>R','R>P'],'P > Q > R','P = 4, Q = 2, and R = 1/2. Dividing by a smaller positive number gives a larger result.','Division by a fraction below 1 increases a positive number.')
relation('mean-versus-midpoint',2,'P = the average of 8 and 20; Q = the average of 11 and 17; R = 15.',{'P':'(8+20)/2','Q':'(11+17)/2','R':'15'},['P < Q','P = Q < R','Q > R','P = R'],['P<Q','P==Q and Q<R','Q>R','P==R'],'P = Q < R','Both pairs total 28, so both averages are 14. Each is less than 15.','Pairs with the same sum have the same average.')
relation('equal-rate-different-whole',2,'P = 3/5 of 50; Q = 3/5 of 45; R = 2/3 of 45.',{'P':'3/5*50','Q':'3/5*45','R':'2/3*45'},['P = Q','P = R > Q','Q > R','P < R'],['P==Q','P==R and R>Q','Q>R','P<R'],'P = R > Q','P = 30, Q = 27, and R = 30. P and R are equal; both exceed Q.','The same fraction of different wholes does not give the same amount.')
relation('decimal-product-size',2,'P = 0.8 × 0.6; Q = 0.8 + 0.6; R = 0.8 − 0.6.',{'P':'8/10*6/10','Q':'8/10+6/10','R':'8/10-6/10'},['P > Q','R > P','Q > P > R','P = R'],['P>Q','R>P','Q>P and P>R','P==R'],'Q > P > R','P = 0.48, Q = 1.4, and R = 0.2. So Q > P > R.','Multiplying two positive decimals below 1 makes a smaller product.')
relation('fractional-sums',3,'P = 1/2 + 1/3; Q = 3/4; R = 5/6.',{'P':'1/2+1/3','Q':'3/4','R':'5/6'},['P = R > Q','P < Q','P > R','Q = R'],['P==R and R>Q','P<Q','P>R','Q==R'],'P = R > Q','P = 3/6 + 2/6 = 5/6, equal to R. In twelfths, 5/6 is 10/12 and 3/4 is 9/12.','Simplify one expression before comparing it with the others.')
relation('percent-change-same-delta',3,'P = the increase from 50 to 60 as a fraction of 50; Q = the decrease from 60 to 50 as a fraction of 60; R = 1/5.',{'P':'(60-50)/50','Q':'(60-50)/60','R':'1/5'},['P = Q','Q > R','P = R > Q','P < Q'],['P==Q','Q>R','P==R and R>Q','P<Q'],'P = R > Q','P is 10/50 = 1/5. Q is 10/60 = 1/6. Equal changes divided by different starting values give different rates.','Always identify the base used in each fraction.')
relation('factor-comparison',1,'P = 12 × 7; Q = 6 × 14; R = 3 × 28.',{'P':'12*7','Q':'6*14','R':'3*28'},['P > Q','R < Q','P = Q = R','Q > R'],['P>Q','R<Q','P==Q and Q==R','Q>R'],'P = Q = R','Each product is 84. Halving one factor while doubling the other leaves the product unchanged.','Use factor compensation instead of multiplying three times.')
relation('absolute-versus-signed',2,'P = the distance from −7 to 0; Q = −7; R = the distance from 3 to −3.',{'P':'7','Q':'-7','R':'3-(-3)'},['P = Q','Q > R','R > P','P > R > Q'],['P==Q','Q>R','R>P','P>R and R>Q'],'P > R > Q','Distances are nonnegative: P = 7 and R = 6. Q is −7, so P > R > Q.','Distance is a length, not a signed coordinate.')
relation('square-versus-product',2,'P = 15²; Q = 14 × 16; R = 13 × 17.',{'P':'15**2','Q':'14*16','R':'13*17'},['P > Q > R','R > Q > P','P = Q','Q < R'],['P>Q and Q>R','R>Q and Q>P','P==Q','Q<R'],'P > Q > R','P = 225, Q = 224, and R = 221. The products decrease as the factors move equally away from 15.','Use (a − b)(a + b) = a² − b² to compare efficiently.')
relation('fraction-of-difference',2,'P = 1/2 of (30 − 12); Q = 1/2 of 30, minus 12; R = 3.',{'P':'(30-12)/2','Q':'30/2-12','R':'3'},['P = Q','P > Q = R','P < R','Q > R'],['P==Q','P>Q and Q==R','P<R','Q>R'],'P > Q = R','P = 18/2 = 9. Q = 15 − 12 = 3, equal to R. The parentheses change what is halved.','Track which part of the expression the fraction applies to.')
relation('fraction-order-signs',3,'P = −2/3; Q = −3/4; R = −5/8.',{'P':'-2/3','Q':'-3/4','R':'-5/8'},['Q > P > R','P > R > Q','R > P > Q','P = Q'],['Q>P and P>R','P>R and R>Q','R>P and P>Q','P==Q'],'R > P > Q','In twenty-fourths, P = −16/24, Q = −18/24, and R = −15/24. The greatest is the one closest to zero.','Use a common denominator, then remember that negative order reverses size intuition.')
assert len(BANK)==84
def visual(family,d,stem,opts,answer,explanation,tip,diagram,proof):
 return new('numeric_comparison','geometric_comparison',family,d,stem,opts,answer,explanation,tip,proof,visual=diagram,answerFormat='relationship' if proof['kind']=='relations' else 'numeric')
visual('grid-fraction-order',2,'Each grid is one whole, divided into equal cells. Let P, Q, and R be the fractions shaded in the labeled grids. Which statement is true?',['P < R < Q','Q < P < R','P = R','R > Q'],'P < R < Q','P = 3/10, Q = 5/12, and R = 2/6 = 1/3. In sixtieths these are 18, 25, and 20, so P < R < Q.','Compare fractions of each whole, not raw numbers of shaded cells.',{'type':'grids','panels':[{'label':'P','rows':2,'cols':5,'shaded':[0,6,9]},{'label':'Q','rows':3,'cols':4,'shaded':[0,2,5,8,11]},{'label':'R','rows':2,'cols':3,'shaded':[1,4]}]}, {'kind':'relations','values':{'P':'3/10','Q':'5/12','R':'2/6'},'predicates':['P<R and R<Q','Q<P and P<R','P==R','R>Q'],'visualCheck':'fractions'})
visual('grid-target',2,'The grid has equal-sized cells. How many additional cells must be shaded so that exactly 2/3 of the grid is shaded?','3|4|5|10','4','There are 15 cells and 6 are shaded. Two thirds of 15 is 10; shade 10 − 6 = 4 additional cells.','Find the target number of shaded cells, then subtract those already shaded.',{'type':'grids','panels':[{'label':'Grid','rows':3,'cols':5,'shaded':[0,2,5,7,10,12]}]}, {'kind':'numeric','expression':'15*2/3-6','visualCheck':'target'})
visual('grid-combined-whole',3,'The two grids are identical and have equal-sized cells. What fraction of all cells in BOTH grids together is shaded?','1/4|1/3|5/12|2/3','1/3','There are 24 cells altogether. The grids have 3 and 5 shaded cells, for 8 shaded cells. Thus 8/24 = 1/3.','When the question combines two wholes, combine their total cell counts too.',{'type':'grids','panels':[{'label':'U','rows':3,'cols':4,'shaded':[0,5,10]},{'label':'V','rows':3,'cols':4,'shaded':[1,3,4,6,9]}]}, {'kind':'numeric','expression':'(3+5)/(12+12)','visualCheck':'combined'})
visual('grid-unshade',1,'Two currently shaded cells are erased. What fraction of the grid will then remain shaded?','1/8|1/4|3/8|1/2','1/4','Six of the 16 cells are currently shaded. Erasing two leaves 4 shaded cells, and 4/16 = 1/4.','The total number of cells stays the same when shading changes.',{'type':'grids','panels':[{'label':'Grid','rows':4,'cols':4,'shaded':[0,2,5,7,8,13]}]}, {'kind':'numeric','expression':'(6-2)/16','visualCheck':'erase'})
visual('bar-combined-comparison',2,'The bars show the number of tickets sold by K, L, and M. Which statement is true?',['K + M < L','K = M','K + M > L','L < K'],'K + M > L','K sold 6, L sold 10, and M sold 8 tickets. K and M together sold 14, which is more than L’s 10.','Read the scale, then compute only the relationship being tested.',{'type':'bars','labels':['K','L','M'],'values':[6,10,8],'maximum':12,'tick':2,'unit':'Tickets'}, {'kind':'relations','values':{'K':'6','L':'10','M':'8'},'predicates':['K+M<L','K==M','K+M>L','L<K'],'visualCheck':'bars'})
visual('bar-missing-total',2,'The chart shows books read from Monday through Thursday. How many books must be read on Friday to make the five-day total 30?','4|5|6|9','6','The four bars total 5 + 9 + 7 + 3 = 24. Friday must add 30 − 24 = 6 books.','Find the total already shown before finding the missing part.',{'type':'bars','labels':['Mon','Tue','Wed','Thu'],'values':[5,9,7,3],'maximum':10,'tick':1,'unit':'Books'}, {'kind':'numeric','expression':'30-(5+9+7+3)','visualCheck':'barTotal'})
visual('bar-average',2,'The bars show the number of points earned in three rounds. How many points above the three-round average is Round B?','1|2|3|4','2','The total is 4 + 10 + 10 = 24, so the average is 8. Round B has 10 points, which is 2 above average.','An average uses every round, including tied values.',{'type':'bars','labels':['A','B','C'],'values':[4,10,10],'maximum':12,'tick':2,'unit':'Points'}, {'kind':'numeric','expression':'10-(4+10+10)/3','visualCheck':'barMean'})
visual('bar-transfer',3,'Two counters are moved from group Q to group R. After the move, which relationship is true?',['P > Q > R','Q > P > R','Q = P','R > Q'],'Q > P > R','The original counts are P = 8, Q = 12, R = 4. After moving two, Q = 10 and R = 6; P stays 8. So Q > P > R.','Update both the giving and receiving group, but leave the third group unchanged.',{'type':'bars','labels':['P','Q','R'],'values':[8,12,4],'maximum':12,'tick':2,'unit':'Counters'}, {'kind':'relations','values':{'P':'8','Q':'12-2','R':'4+2'},'predicates':['P>Q and Q>R','Q>P and P>R','Q==P','R>Q'],'visualCheck':'barTransfer'})
visual('equal-perimeter-distinct-area',2,'P is a rectangle and Q is a square with the dimensions shown. Which statement is true?',['P has a larger perimeter than Q','They have equal perimeters, but Q has the larger area','They have equal areas','Q has a smaller area than P'],'They have equal perimeters, but Q has the larger area','P has perimeter 2(7 + 3) = 20 and area 21. Q has perimeter 4 × 5 = 20 and area 25. The perimeters match, but Q has more area.','Perimeter and area measure different things; compare them separately.',{'type':'rectangles','panels':[{'label':'P','width':7,'height':3},{'label':'Q','width':5,'height':5}],'unit':'cm'}, {'kind':'relations','values':{'PP':'2*(7+3)','QP':'4*5','PA':'7*3','QA':'5*5'},'predicates':['PP>QP','PP==QP and QA>PA','PA==QA','QA<PA'],'visualCheck':'rectangles'})
visual('rectangle-perimeter-gap',2,'Both figures are rectangles. How many centimetres greater is the perimeter of T than the perimeter of S?','2|4|6|8','4','S has perimeter 2(6 + 2) = 16 cm. T has perimeter 2(7 + 3) = 20 cm. The difference is 4 cm.','Both pairs of sides count toward a rectangle’s perimeter.',{'type':'rectangles','panels':[{'label':'S','width':6,'height':2},{'label':'T','width':7,'height':3}],'unit':'cm'}, {'kind':'numeric','expression':'2*(7+3)-2*(6+2)','visualCheck':'perimeterGap'})
visual('rectangle-area-ratio',2,'The dimensions are in centimetres. What fraction of rectangle W’s area is rectangle V’s area?','1/4|1/3|1/2|2/3','1/2','V has area 4 × 3 = 12. W has area 8 × 3 = 24. The ratio of V’s area to W’s area is 12/24 = 1/2.','With equal heights, the area ratio equals the width ratio.',{'type':'rectangles','panels':[{'label':'V','width':4,'height':3},{'label':'W','width':8,'height':3}],'unit':'cm'}, {'kind':'numeric','expression':'4*3/(8*3)','visualCheck':'areaRatio'})
visual('rectangle-square-area',2,'A square will have the same area as the rectangle shown. What must the square’s side length be, in centimetres?','4|6|8|9','6','The rectangle has area 9 × 4 = 36 square centimetres. A square of side 6 has area 6 × 6 = 36.','Match areas first, then find the square root to get a side length.',{'type':'rectangles','panels':[{'label':'Rectangle','width':9,'height':4}],'unit':'cm'}, {'kind':'numeric','expression':'6','visualCheck':'squareSide'})
visual('straight-angle-missing',1,'A, O, and B lie on a straight line. The marked angle AOC is 68°. What is angle COB, in degrees?','22|68|112|122','112','The two adjacent angles form a straight angle of 180°. Subtract 68° to get 112°.','Adjacent angles on a straight line add to 180°.',{'type':'angles','layout':'straight','known':68,'labels':['A','O','B','C']}, {'kind':'numeric','expression':'180-68','visualCheck':'straight'})
visual('right-angle-split',1,'The square mark shows that angle POQ is a right angle. Ray OR divides it, and angle POR is 34°. What is angle ROQ, in degrees?','34|46|56|146','56','A right angle is 90°. The remaining angle is 90 − 34 = 56°.','Use the right-angle mark, not an estimate of the drawing.',{'type':'angles','layout':'right','known':34,'labels':['P','O','Q','R']}, {'kind':'numeric','expression':'90-34','visualCheck':'right'})
visual('straight-three-parts',2,'A, O, and B lie on a straight line. The two marked adjacent angles are 42° and 65°. What is the remaining angle x, in degrees?','65|73|83|107','73','All three adjacent angles total 180°. The known angles total 107°, so x = 180 − 107 = 73°.','Subtract the sum of the known angles, not their difference.',{'type':'angles','layout':'three','known':[42,65],'labels':['A','O','B','C','D']}, {'kind':'numeric','expression':'180-42-65','visualCheck':'three'})
visual('right-angle-ratio',3,'The square mark shows a right angle split into the two adjacent angles labeled x and 2x. What is the larger angle, in degrees?','30|45|60|90','60','The two angles total 90°, so x + 2x = 90°. Three equal parts total 90°, making x = 30° and 2x = 60°.','Count equal parts before calculating the requested angle.',{'type':'angles','layout':'ratio','known':[1,2],'labels':['P','O','Q','R']}, {'kind':'numeric','expression':'90/3*2','visualCheck':'ratio'})
assert len(BANK)==100
OUT.mkdir(parents=True,exist_ok=True)
(OUT/'bank.json').write_text(json.dumps(BANK,ensure_ascii=False,indent=2)+'\n')
(OUT/'proofs.json').write_text(json.dumps(PROOFS,ensure_ascii=False,indent=2)+'\n')
(OUT/'changes.json').write_text(json.dumps(CHANGES,ensure_ascii=False,indent=2)+'\n')
print('Staged 100 questions; live app unchanged.')
