import {useEffect,useRef,useState} from 'react';
import {skills,type Session,type Skill} from './domain/types';
import {complete,createSession,remaining} from './domain/session';
import {loadPreferences,savePreferences,saveSession,loadProgress,loadBank,beginPractice,probeStorage,deriveExposures,type InstalledBank} from './domain/storage';
import {availableQuestions,pickFresh,type Exposure} from './domain/freshSelection';
import {checkForBank} from './domain/bankDelivery';
import {validateBank} from './domain/contentSchema.mjs';
import Test from './components/Test';
import Results from './components/Results';
import ProgressSettings from './components/ProgressSettings';
export default function App(){
 const [page,setPage]=useState<'home'|'setup'|'test'|'done'|'settings'>('home');const [session,setSession]=useState<Session|null>(null);const current=useRef(session);
 const [saved,setSaved]=useState<Session[]>([]),[exposures,setExposures]=useState<Exposure[]>([]),[installed,setInstalled]=useState<InstalledBank|null>(null);
 const [loading,setLoading]=useState(true),[checking,setChecking]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),[bankStatus,setBankStatus]=useState('Checking for questions…'),[storageFailed,setStorageFailed]=useState(false),[temporary,setTemporary]=useState(false);
 const [mode,setMode]=useState<Session['mode']>('timed'),[skill,setSkill]=useState<Skill|'mixed'>('mixed'),[review,setReview]=useState(false),[short,setShort]=useState(false),[prefs,setPrefs]=useState(loadPreferences);
 const audio=useRef<AudioContext|null>(null),queue=useRef(Promise.resolve()),channel=useRef<BroadcastChannel|null>(null);
 async function refresh(){const data=await loadProgress();setSaved(data.sessions);setExposures(data.exposures);channel.current?.postMessage('progress');}
 async function check(){setChecking(true);try{const bank=await checkForBank();setInstalled(bank);setBankStatus('Questions are up to date.');}catch(e){const downloaded=(e as {downloadedBank?:InstalledBank}).downloadedBank;if(downloaded){setInstalled(old=>old??downloaded);setStorageFailed(true);}setBankStatus('Could not save or check new questions. Your last saved bank is still available. Retry when connected and storage is available.');}finally{setChecking(false);}}
 useEffect(()=>{let live=true;void loadProgress().then(data=>{if(live){setSaved(data.sessions);setExposures(data.exposures);}}).catch(e=>{if(live){setStorageFailed(true);setError(e instanceof Error?e.message+' Retry storage or choose temporary practice.':'Progress storage is unavailable. Retry, or explicitly choose temporary practice.');}}).finally(()=>{if(live)setLoading(false);});void loadBank().then(bank=>{if(live&&bank){validateBank(bank.bank,bank.manifest);setInstalled(bank);}}).catch(()=>{}).finally(()=>{if(live)void check();});
 const sync=()=>{void queue.current.then(()=>loadProgress()).then(data=>{if(!live)return;setSaved(data.sessions);setExposures(data.exposures);const latest=data.sessions.find(s=>s.id===current.current?.id);if(!latest&&current.current?.status==='active'&&!current.current.temporary){current.current=null;setSession(null);setPage('home');}if(latest&&current.current?.status==='active'){current.current=latest;setSession(latest);if(latest.status!=='active')setPage('done');}}).catch(()=>{});};
 if(typeof BroadcastChannel!=='undefined'){channel.current=new BroadcastChannel('hspt-progress');channel.current.onmessage=sync;}window.addEventListener('focus',sync);return()=>{live=false;channel.current?.close();window.removeEventListener('focus',sync);};},[]);
 function persist(s:Session,base?:Session){if(s.temporary)return;queue.current=queue.current.then(async()=>{const stored=await saveSession(s,base);setStorageFailed(false);setError('');if(current.current===s){current.current=stored;setSession(stored);if(stored.status!=='active'&&s.status==='active')setPage('done');}const data=await loadProgress();setSaved(data.sessions);setExposures(data.exposures);channel.current?.postMessage('progress');}).catch(()=>{setStorageFailed(true);setError('Your latest progress could not be saved. Keep this page open and retry saving before leaving.');});}
 function update(s:Session){const base=current.current??undefined;current.current=s;setSession(s);persist(s,base);}
 function unlock(){try{const Audio=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;audio.current??=new Audio();void audio.current.resume().catch(()=>{});}catch{}}
 function sound(){try{const a=audio.current;if(!a||a.state!=='running')return;const o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=660;g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.5);o.start();o.stop(a.currentTime+.5);}catch{}}
 function finish(){const s=current.current;if(!s||s.status!=='active')return;const done=complete(s);update(done);setSaved(old=>[...old.filter(x=>x.id!==done.id),done]);if(done.status==='expired')sound();setPage('done');}
 function toggle(){setPrefs(p=>{const next={timerVisible:!p.timerVisible};savePreferences(next);return next;});}
 const questions=installed?.bank.questions??[];const activeSkills=[...new Set(questions.map(q=>q.skill))];const unfinished=saved.find(s=>s.status==='active');
 const eligible=availableQuestions(questions,skill,exposures,saved,Date.now(),review);const total=questions.filter(q=>skill==='mixed'||q.skill===skill).length;const selectedCount=Math.min(10,eligible.length);const mayStart=selectedCount>0&&(selectedCount===10||short)&&( !storageFailed||temporary);
 function setup(m:Session['mode'],focus:Skill|'mixed'='mixed'){setMode(m);setSkill(focus);setReview(false);setShort(false);setPage('setup');}
 async function start(){unlock();setStarting(true);setError('');try{await queue.current;const s=temporary&&storageFailed?{...createSession(pickFresh(questions,skill,exposures,saved,selectedCount,review),mode,skill),temporary:true,bankRelease:installed?.manifest.releaseId,practiceKind:review?'review' as const:'ordinary' as const}:await beginPractice(skill,mode,selectedCount,review);current.current=s;setSession(s);if(!s.temporary)await refresh();else{setExposures(deriveExposures([...saved,s],exposures));setSaved(old=>[...old,s]);}if(remaining(s)===0)finish();else setPage('test');}catch(e){setError(e instanceof Error?e.message:'Unable to save a new session.');if(!(e instanceof Error&&e.message.startsWith('Available questions')))setStorageFailed(true);void refresh().catch(()=>setStorageFailed(true));}finally{setStarting(false);}}
 async function resume(){if(!unfinished)return;unlock();try{const data=await loadProgress();const latest=data.sessions.find(s=>s.id===unfinished.id);if(!latest){await refresh();return;}current.current=latest;setSession(latest);if(latest.status!=='active')setPage('done');else if(remaining(latest)===0)finish();else setPage('test');}catch{setStorageFailed(true);setError('Could not restore saved practice. Retry storage.');}}
 async function retryStorage(){try{await queue.current;await probeStorage();if(current.current&&!current.current.temporary)await saveSession(current.current);await refresh();setStorageFailed(false);setError('');}catch{setStorageFailed(true);setError('Storage is still unavailable. Keep this page open or export a backup if possible.');}}

 const warning=<>{error&&<div role="alert" className="storage-error">{error} <button onClick={()=>void retryStorage()}>Retry saving</button></div>}</>;
 if(page==='test'&&session)return <>{warning}<Test session={session} visible={prefs.timerVisible} toggle={toggle} onChange={update} onFinish={finish}/></>;
 return <div className="shell"><header className="brand"><a href="#" onClick={e=>{e.preventDefault();setPage('home');}}><span className="brand-mark">H</span> HSPT <span className="brand-light">Practice</span></a><button className="text-button" onClick={()=>setPage('settings')}>History & settings</button></header>{warning}<main className="content">
 {page==='settings'?<><button className="text-button" onClick={()=>setPage('home')}>← Home</button><ProgressSettings sessions={saved} installed={installed} status={bankStatus} checking={checking} onCheck={()=>void check()} onRefresh={refresh} onReview={s=>{setSession(s);setPage('done');}}/></>:page==='home'?<>
 <div className="intro"><span className="eyebrow">A LITTLE PRACTICE, A CLEARER MIND</span><h1>Make room for<br/>five focused minutes.</h1><p>Build confidence with numbers, one short practice at a time.</p></div>
 {unfinished&&<section className="resume"><div><strong>You have unfinished practice.</strong><p>Your saved questions and original deadline are preserved.</p></div><button className="primary" onClick={resume}>Resume practice</button></section>}
 {!installed&&<div className="notice" role="status"><p>{checking?'Downloading your question bank…':'No question bank is available yet. Connect to the internet and retry.'}</p><button disabled={checking} onClick={()=>void check()}>Retry question download</button></div>}
 <section className="start-card"><div className="subject-icon">01</div><div className="start-copy"><span className="eyebrow">QUANTITATIVE SKILLS</span><h2>A small set. Your full attention.</h2><p>Number patterns, comparisons, and reasoning.</p><div className="facts"><span>Up to 10 questions</span><span>5 minutes</span><span>Paper-style practice</span></div><button className="primary large" disabled={loading||!!unfinished||!installed} onClick={()=>setup('timed')}>Start 5-minute Quantitative burst →</button></div></section>
 <div className="secondary-actions"><button disabled={loading||!!unfinished||!installed} onClick={()=>setup('timed')}>Choose a skill <span>Focus on one kind of question →</span></button><button disabled={loading||!!unfinished||!installed} onClick={()=>setup('untimed')}>Untimed practice <span>Take the time you need →</span></button></div>
 <aside className="development"><strong>{questions.length} questions · Human sample reviewed</strong><p>{bankStatus}</p><p>Answers and progress stay on this device. Keep a backup in History & settings.</p></aside>
 </>:page==='setup'?<><button className="text-button back" onClick={()=>setPage('home')}>← Back to home</button><span className="eyebrow">MAKE IT YOUR PRACTICE</span><h1>Ready when you are.</h1><section className="setup-card"><label htmlFor="skill">Practice focus</label><select id="skill" value={skill} onChange={e=>{setSkill(e.target.value as Skill|'mixed');setReview(false);setShort(false);}}><option value="mixed">Mixed quantitative skills</option>{activeSkills.map(id=><option key={id} value={id}>{skills[id]}</option>)}</select>
 <fieldset><legend>Practice mode</legend><label className="radio"><input type="radio" checked={mode==='timed'} onChange={()=>setMode('timed')}/> Five-minute burst</label><label className="radio"><input type="radio" checked={mode==='untimed'} onChange={()=>setMode('untimed')}/> Untimed practice</label></fieldset>
 <label className="checkbox"><input type="checkbox" checked={prefs.timerVisible} onChange={toggle}/> Show timer when practice starts</label>
 <p>{eligible.length} questions available {review?'for review':'without breaking the repeat cooldown'}.</p><p className="muted">Previously seen questions wait at least 14 days and five subsequent completed practices. New questions are used first.</p>
 <label className="checkbox"><input type="checkbox" checked={review} onChange={e=>{setReview(e.target.checked);setShort(false);}}/> Review set — allow recently seen questions</label>
 {selectedCount<10&&<div className="notice">{selectedCount>0?<label className="checkbox"><input type="checkbox" checked={short} onChange={e=>setShort(e.target.checked)}/> Start a shorter set of {selectedCount} questions</label>:<p>No eligible questions remain. Choose review or another focus.</p>}{!review&&<p>A review set can draw from all {total} questions in this focus.</p>}</div>}
 {storageFailed&&<div className="notice"><p>Progress cannot currently be saved. Retry storage, or continue temporarily. Temporary sessions are lost when this page closes.</p><button onClick={()=>void retryStorage()}>Retry storage</button><label className="checkbox"><input type="checkbox" checked={temporary} onChange={e=>setTemporary(e.target.checked)}/> I understand — practice without saving</label></div>}
 <div className="summary"><span><strong>{selectedCount}</strong> questions</span><span><strong>{mode==='timed'?'5:00':'No limit'}</strong> {mode==='timed'?'time limit':'untimed'}</span><span><strong>{review?'Review':'Fresh practice'}</strong> {prefs.timerVisible?'Timer visible':'Timer hidden'}</span></div><p className="muted">Hiding the timer does not pause it. Shorter timed sets still have five minutes.</p><button className="primary large" disabled={!mayStart||starting} onClick={()=>void start()}>{starting?'Saving practice…':`Begin ${review?'review set':mode==='timed'?'5-minute burst':'untimed practice'} →`}</button></section></>:session&&<Results key={session.id} session={session} onHome={()=>setPage('home')} onPractice={focus=>setup('timed',activeSkills.includes(focus)?focus:'mixed')}/>}
 </main><footer>HSPT Practice <span>Independent practice · No accounts or tracking</span></footer></div>;
}
