import {testOrder,questionSection,planSession,visibleSession,finishPart,advancePart,sessionTitle} from './domain/testPlan';
import {sections,type Section,type TestKind} from './domain/types';
import {useEffect,useRef,useState} from 'react';
import {skills,type Session,type Skill} from './domain/types';
import {remaining} from './domain/session';
import {loadPreferences,savePreferences,saveSession,loadProgress,loadBank,beginPlannedPractice,probeStorage,deriveExposures,type InstalledBank} from './domain/storage';
import {availableQuestions,pickFresh,type Exposure} from './domain/freshSelection';
import {checkForBank} from './domain/bankDelivery';
import {validateBank} from './domain/contentSchema.mjs';
import Test from './components/Test';
import Results from './components/Results';
import ProgressSettings from './components/ProgressSettings';
export default function App(){
 const [page,setPage]=useState<'home'|'setup'|'test'|'done'|'settings'|'choose'|'progress'>('home');const [session,setSession]=useState<Session|null>(null);const current=useRef(session);
 const [saved,setSaved]=useState<Session[]>([]),[exposures,setExposures]=useState<Exposure[]>([]),[installed,setInstalled]=useState<InstalledBank|null>(null);
 const [loading,setLoading]=useState(true),[checking,setChecking]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState(''),[bankStatus,setBankStatus]=useState('Checking for questions…'),[storageFailed,setStorageFailed]=useState(false),[temporary,setTemporary]=useState(false);
 const [mode,setMode]=useState<Session['mode']>('timed'),[skill,setSkill]=useState<Skill|'mixed'>('mixed'),[review,setReview]=useState(false),[short,setShort]=useState(false),[prefs,setPrefs]=useState(loadPreferences);
 const [section,setSection]=useState<Section>('quantitative'),[kind,setKind]=useState<TestKind>('burst');
 const audio=useRef<AudioContext|null>(null),queue=useRef(Promise.resolve()),channel=useRef<BroadcastChannel|null>(null);
 async function refresh(){const data=await loadProgress();setSaved(data.sessions);setExposures(data.exposures);channel.current?.postMessage('progress');}
 async function check(){setChecking(true);try{const bank=await checkForBank();setInstalled(bank);setBankStatus('Questions are up to date.');}catch(e){const downloaded=(e as {downloadedBank?:InstalledBank}).downloadedBank;if(downloaded){setInstalled(old=>old??downloaded);setStorageFailed(true);}setBankStatus('Could not save or check new questions. Your last saved bank is still available. Retry when connected and storage is available.');}finally{setChecking(false);}}
 useEffect(()=>{let live=true;void loadProgress().then(data=>{if(live){setSaved(data.sessions);setExposures(data.exposures);}}).catch(e=>{if(live){setStorageFailed(true);setError(e instanceof Error?e.message+' Retry storage or choose temporary practice.':'Progress storage is unavailable. Retry, or explicitly choose temporary practice.');}}).finally(()=>{if(live)setLoading(false);});void loadBank().then(bank=>{if(live&&bank){validateBank(bank.bank,bank.manifest);setInstalled(bank);}}).catch(()=>{}).finally(()=>{if(live)void check();});
 const sync=()=>{void queue.current.then(()=>loadProgress()).then(data=>{if(!live)return;setSaved(data.sessions);setExposures(data.exposures);const latest=data.sessions.find(s=>s.id===current.current?.id);if(!latest&&current.current?.status==='active'&&!current.current.temporary){current.current=null;setSession(null);setPage('home');}if(latest&&current.current?.status==='active'){current.current=latest;setSession(latest);if(latest.status!=='active')setPage('done');}}).catch(()=>{});};
 if(typeof BroadcastChannel!=='undefined'){channel.current=new BroadcastChannel('hspt-progress');channel.current.onmessage=sync;}window.addEventListener('focus',sync);return()=>{live=false;channel.current?.close();window.removeEventListener('focus',sync);};},[]);
 function persist(s:Session,base?:Session){if(s.temporary)return;queue.current=queue.current.then(async()=>{const stored=await saveSession(s,base);setStorageFailed(false);setError('');if(current.current===s){current.current=stored;setSession(stored);if(stored.status!=='active'&&s.status==='active')setPage('done');}const data=await loadProgress();setSaved(data.sessions);setExposures(data.exposures);channel.current?.postMessage('progress');}).catch(()=>{setStorageFailed(true);setError('Your latest progress could not be saved. Keep this page open and retry saving before leaving.');});}
 function update(s:Session){const base=current.current??undefined;current.current=s;setSession(s);persist(s,base);}
 function unlock(){try{const Audio=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;audio.current??=new Audio();void audio.current.resume().catch(()=>{});}catch{}}
 function sound(){try{const a=audio.current;if(!a||a.state!=='running')return;const o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=660;g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.5);o.start();o.stop(a.currentTime+.5);}catch{}}
 function finish(){const s=current.current;if(!s||s.status!=='active')return;const done=finishPart(s);update(done);setSaved(old=>[...old.filter(x=>x.id!==done.id),done]);if(s.deadlineAt!==undefined&&Date.now()>=s.deadlineAt)sound();setPage(done.status==='active'?'test':'done');}
 function toggle(){setPrefs(p=>{const next={timerVisible:!p.timerVisible};savePreferences(next);return next;});}
 const bankQuestions=installed?.bank.questions??[];const questions=bankQuestions.filter(q=>questionSection(q)===section);const activeSkills=[...new Set(questions.map(q=>q.skill))];const unfinished=saved.find(s=>s.status==='active');
 const eligible=availableQuestions(questions,skill,exposures,saved,Date.now(),review);const total=questions.filter(q=>skill==='mixed'||q.skill===skill).length;const selectedCount=kind==='full'?50:pickFresh(questions,skill,exposures,saved,10,review,Date.now(),()=>0.5).length;const fullReady=testOrder.every(part=>pickFresh(bankQuestions.filter(q=>questionSection(q)===part),'mixed',exposures,saved,10,review,Date.now(),()=>0.5).length===10);const mayStart=(kind==='full'?fullReady:selectedCount>0&&(selectedCount===10||(kind==='burst'&&short)))&&(!storageFailed||temporary);
 function setup(m:Session['mode'],focus:Skill|'mixed'='mixed',target:Section=section){setMode(m);setSection(target);setSkill(focus);setReview(false);setShort(false);setPage('setup');}
 function choose(next:TestKind){setKind(next);setSkill('mixed');setReview(false);setShort(false);setMode('timed');setPage(next==='full'?'setup':'choose');}
 async function nextPart(){const s=current.current;if(!s)return;setStarting(true);try{await queue.current;const next=advancePart(s);if(s.temporary){current.current=next;setSession(next);}else{const stored=await saveSession(next,s);current.current=stored;setSession(stored);await refresh();}}catch{setError('Could not start the next section. Retry saving.');}finally{setStarting(false);}}
 async function start(){unlock();setStarting(true);setError('');try{await queue.current;const s=temporary&&storageFailed?{...planSession((kind==='full'?testOrder:[section]).map(part=>({section:part,questions:pickFresh(bankQuestions.filter(q=>questionSection(q)===part),kind==='full'?'mixed':skill,exposures,saved,kind==='full'?10:selectedCount,review)})),kind,mode),temporary:true,bankRelease:installed?.manifest.releaseId,practiceKind:review?'review' as const:'ordinary' as const}:await beginPlannedPractice(section,kind,mode,selectedCount,review,Date.now(),skill);current.current=s;setSession(s);if(!s.temporary)await refresh();else{setExposures(deriveExposures([...saved,s],exposures));setSaved(old=>[...old,s]);}if(remaining(s)===0)finish();else setPage('test');}catch(e){setError(e instanceof Error?e.message:'Unable to save a new session.');if(!(e instanceof Error&&e.message.startsWith('Available questions')))setStorageFailed(true);void refresh().catch(()=>setStorageFailed(true));}finally{setStarting(false);}}
 async function resume(){if(!unfinished)return;unlock();try{const data=await loadProgress();const latest=data.sessions.find(s=>s.id===unfinished.id);if(!latest){await refresh();return;}current.current=latest;setSession(latest);if(latest.status!=='active')setPage('done');else if(remaining(latest)===0)finish();else setPage('test');}catch{setStorageFailed(true);setError('Could not restore saved practice. Retry storage.');}}
 async function retryStorage(){try{await queue.current;await probeStorage();if(current.current&&!current.current.temporary)await saveSession(current.current);await refresh();setStorageFailed(false);setError('');}catch{setStorageFailed(true);setError('Storage is still unavailable. Keep this page open or export a backup if possible.');}}

 const warning=<>{error&&<div role="alert" className="storage-error">{error} <button onClick={()=>void retryStorage()}>Retry saving</button></div>}</>;
 if(page==='test'&&session){
  if(session.stage==='break'&&session.parts)return <div className="shell">{warning}<main className="content"><span className="eyebrow">FULL TEST PREVIEW · SECTION {(session.partIndex??0)+1} OF {session.parts.length} COMPLETE</span><h1>Take a short break.</h1><p>{session.parts[session.partIndex??0].expired?'Time expired for that section. Your answers are saved.':'Your answers are saved.'} The next timer starts only when you continue.</p><section className="setup-card"><h2>Next: {sections[session.parts[(session.partIndex??0)+1].section]}</h2><p>10 questions · {session.mode==='timed'?'5-minute preview timer':'Untimed'} · Preview lengths are not official exam timings.</p><button className="primary" disabled={starting} onClick={()=>void nextPart()}>Start next section →</button> <button onClick={()=>setPage('home')}>Return home — resume later</button></section></main></div>;
  const visible=visibleSession(session);return <>{warning}<Test key={`${session.id}-${session.partIndex??0}`} session={visible} visible={prefs.timerVisible} toggle={toggle} onChange={part=>update({...session,responses:{...session.responses,...part.responses}})} onFinish={finish}/></>;
 }
 return <div className="shell"><header className="brand"><a href="#" onClick={e=>{e.preventDefault();setPage('home');}}><span className="brand-mark">H</span> HSPT <span className="brand-light">Practice</span></a><nav className="main-nav" aria-label="Main navigation">{(['home','progress','settings'] as const).map(p=><button key={p} aria-current={page===p?'page':undefined} className="text-button" onClick={()=>setPage(p)}>{p==='home'?'Practice':p==='progress'?'Progress':'Settings'}</button>)}</nav></header>{warning}<main className="content">
 {page==='settings'||page==='progress'?<><button className="text-button" onClick={()=>setPage('home')}>← Home</button><ProgressSettings view={page} sessions={saved} installed={installed} status={bankStatus} checking={checking} onCheck={()=>void check()} onRefresh={refresh} onReview={s=>{setSession(s);setPage('done');}}/></>:page==='home'?<>
 <div className="intro"><span className="eyebrow">MAKE A LITTLE ROOM FOR PROGRESS</span><h1>How would you like<br/>to practice today?</h1><p>A few focused minutes, a section, or a preview of the whole test.</p></div>
 {unfinished&&<section className="resume"><div><strong>You have unfinished practice.</strong><p>{sessionTitle(unfinished)} · {unfinished.stage==='break'?'Between sections':'Original deadline preserved'}</p></div><button className="primary" onClick={resume}>Resume practice →</button></section>}
 <div className="practice-modes">{([{id:'burst',title:'5-minute practice',tag:'A LITTLE, OFTEN',description:'Build a skill with a short set of questions.'},{id:'section',title:'Section test',tag:'FIND YOUR RHYTHM',description:'Explore one section with a 10-question preview.'},{id:'full',title:'Full practice test',tag:'PUT IT ALL TOGETHER',description:'Try all five sections. 50 questions, with breaks.'}] as const).map(item=><section className="mode-card" key={item.id}><span className="eyebrow">{item.tag}</span><h2>{item.title}</h2><p>{item.description}</p><button className={item.id==='burst'?'primary':''} disabled={loading||!!unfinished} onClick={()=>choose(item.id)}>{item.id==='full'?'View test overview':'Choose a section'} →</button></section>)}</div>
 <div className="quick-practice"><span>Pick up your usual practice</span><button className="text-button" disabled={loading||!!unfinished} onClick={()=>{setKind('burst');setup('timed','mixed','quantitative');}}>5-minute Quantitative practice →</button></div>
 <aside className="development"><strong>Practice across all five sections</strong><p>100 questions per section, with answer explanations and reviewed samples. Section and full-test previews use shortened practice timing, not official exam lengths.</p><p>{bankStatus}</p>{!installed&&<button disabled={checking} onClick={()=>void check()}>Download question bank</button>}</aside>
 </>:page==='choose'?<><button className="text-button" onClick={()=>setPage('home')}>← Practice</button><span className="eyebrow">{kind==='burst'?'5-MINUTE PRACTICE':'SECTION TEST PREVIEW'}</span><h1>Choose your section.</h1><div className="section-grid">{Object.entries(sections).map(([id,label])=><button key={id} onClick={()=>setup('timed','mixed',id as Section)}><strong>{label}</strong><span>{`${bankQuestions.filter(q=>questionSection(q)===id).length} questions`}</span><span aria-hidden="true">→</span></button>)}</div></>
 :page==='setup'?<><button className="text-button back" onClick={()=>setPage('home')}>← Back to home</button><span className="eyebrow">{kind==='full'?'FULL TEST PREVIEW':kind==='section'?'SECTION TEST PREVIEW':'5-MINUTE PRACTICE'}</span><h1>{kind==='full'?'Make space for all five sections.':`${sections[section]}, at your pace.`}</h1><section className="setup-card">
 {kind==='full'?<><ol className="section-order">{testOrder.map(part=><li key={part}>{sections[part]} <span>10 questions · 5 minutes</span></li>)}</ol><p>50 questions · 25 minutes of timed practice, plus optional breaks between sections. This is an illustrative preview order and timing, not a full-length exam simulation.</p><p className="notice">All five sections use sample-reviewed practice banks. Results show practice accuracy, not an official HSPT score.</p></>:kind==='section'?<p className="notice">This 10-question section preview uses a 5-minute practice timer, not official section timing.</p>:null}
 {kind==='burst'&&activeSkills.length>1&&<><label htmlFor="skill">Practice focus</label><select id="skill" value={skill} onChange={e=>{setSkill(e.target.value as Skill|'mixed');setReview(false);setShort(false);}}><option value="mixed">Mixed skills</option>{activeSkills.map(id=><option key={id} value={id}>{skills[id]}</option>)}</select></>}
 {kind!=='full'&&<fieldset><legend>Practice mode</legend><label className="radio"><input type="radio" checked={mode==='timed'} onChange={()=>setMode('timed')}/> Five-minute preview timer</label><label className="radio"><input type="radio" checked={mode==='untimed'} onChange={()=>setMode('untimed')}/> Untimed practice</label></fieldset>}
 <label className="checkbox"><input type="checkbox" checked={prefs.timerVisible} onChange={toggle}/> Show timer when practice starts</label>
 {section==='reading'&&kind!=='full'&&<p className="muted">Passage questions stay together. A comprehension focus includes the complete passage group; mixed sets add vocabulary when space allows.</p>}{kind!=='full'&&<p>{eligible.length} questions available {review?'for review':'without breaking the repeat cooldown'}.</p>}<p className="muted">Previously seen questions wait at least 14 days and five subsequent completed practices. New questions are used first.</p>
 <label className="checkbox"><input type="checkbox" checked={review} onChange={e=>{setReview(e.target.checked);setShort(false);}}/> Review set — allow recently seen questions</label>
 {kind==='full'&&!fullReady&&<p className="notice">Each section needs 10 available questions. Enable review if you have already practiced these questions, and ensure the question bank is up to date.</p>}{kind!=='full'&&selectedCount<10&&<div className="notice">{selectedCount>0&&kind==='burst'?<label className="checkbox"><input type="checkbox" checked={short} onChange={e=>setShort(e.target.checked)}/> Start a shorter set of {selectedCount} questions</label>:<p>Not enough eligible questions for this set. Choose review or another focus.</p>}{!review&&<p>A review set can draw from all {total} questions in this focus.</p>}</div>}
 {storageFailed&&<div className="notice"><p>Progress cannot currently be saved. Retry storage, or continue temporarily. Temporary sessions are lost when this page closes.</p><button onClick={()=>void retryStorage()}>Retry storage</button><label className="checkbox"><input type="checkbox" checked={temporary} onChange={e=>setTemporary(e.target.checked)}/> I understand — practice without saving</label></div>}
 <div className="summary"><span><strong>{selectedCount}</strong> questions</span><span><strong>{mode==='timed'?(kind==='full'?'5:00 per section':'5:00'):'No limit'}</strong> {mode==='timed'?'time limit':'untimed'}</span><span><strong>{review?'Review':'Fresh practice'}</strong> {prefs.timerVisible?'Timer visible':'Timer hidden'}</span></div><p className="muted">Hiding the timer does not pause it. Shorter timed sets still have five minutes.</p><button className="primary large" disabled={!mayStart||starting} onClick={()=>void start()}>{starting?'Saving practice…':`Begin ${review?'review set':kind==='full'?'full test preview':kind==='section'?'section preview':mode==='timed'?'5-minute burst':'untimed practice'} →`}</button></section></>:session&&<Results key={session.id} session={session} onHome={()=>setPage('home')} onPractice={focus=>{const target=questionSection(session.questions.find(q=>q.skill===focus)!);setKind('burst');setup('timed',focus,target);}}/>}
 </main><footer>HSPT Practice <span>Independent practice · No accounts or tracking</span></footer></div>;
}
